# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 08:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0003_add_matcher_name_fields'),
    ]

    operations = []
