# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_jobs_submit_time_repository_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='expire_performance_data',
            field=models.BooleanField(default=True),
        ),
    ]
