# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 09:40
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_remove_m2m_between_classified_failures_and_failure_match'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='failurematch', unique_together=set([]),),
        migrations.RemoveField(model_name='failurematch', name='classified_failure',),
        migrations.RemoveField(model_name='failurematch', name='failure_line',),
        migrations.DeleteModel(name='FailureMatch',),
    ]
