# Generated by Django 1.11.15 on 2018-09-18 18:21
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0008_remove_failure_match'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='push',
            managers=[
                ('failures', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('failures', django.db.models.manager.Manager()),
            ],
        ),
    ]
