# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_push_job_child_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_try_repo',
            field=models.BooleanField(default=False),
        ),
    ]
