# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 18:21
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_remove_failure_match'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='push', managers=[('failures', django.db.models.manager.Manager()),],
        ),
        migrations.AlterModelManagers(
            name='job', managers=[('failures', django.db.models.manager.Manager()),],
        ),
    ]
