# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_remove_failure_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failureline',
            name='best_classification',
        ),
        migrations.RemoveField(
            model_name='failureline',
            name='best_is_verified',
        ),
    ]
