# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_remove_failureline_best_classification_fk_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failureline',
            name='best_classification',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_lines', to='model.ClassifiedFailure'),
        ),
        migrations.RunSQL(
            'ALTER TABLE `failure_line` DROP COLUMN `best_classification_id`, DROP COLUMN `best_is_verified`;',
            state_operations=[
                migrations.RemoveField(
                    model_name='failureline',
                    name='best_classification',
                ),
                migrations.RemoveField(
                    model_name='failureline',
                    name='best_is_verified',
                ),
            ],
        )
    ]
