# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 11:26
from __future__ import unicode_literals

import django
from django.db import (migrations,
                       models)


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_rename_classified_failure_to_classification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FailureClassification',
            new_name='FailureType',
        ),
        migrations.AlterField(
            model_name='job',
            name='failure_classification',
            field=models.ForeignKey(db_column='failure_classification_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='model.FailureType'),
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='failure_classification',
            field=models.ForeignKey(db_column='failure_classification_id', on_delete=django.db.models.deletion.CASCADE, to='model.FailureType'),
        ),
        migrations.RenameField(
            model_name='job',
            old_name='failure_classification',
            new_name='failure_type',
        ),
        migrations.RenameField(
            model_name='jobnote',
            old_name='failure_classification',
            new_name='failure_type',
        ),
    ]
