# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 09:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_remove_runnable_job'),
    ]

    operations = [
        migrations.DeleteModel(name='Matcher',),
    ]
