# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_remove_TextLogSummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('failure_lines', models.ManyToManyField(related_name='group', to='model.FailureLine')),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
