# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_create_group'),
    ]

    # Must make these migrations a DB noop because of this Django Bug:
    # https://code.djangoproject.com/ticket/25253

    operations = [
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='failureline',
                    name='job_log',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failure_line', to='model.JobLog'),
                ),
            ],
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='job',
                    name='build_platform',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='model.BuildPlatform'),
                ),
            ],
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='job',
                    name='failure_classification',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='model.FailureClassification'),
                ),
            ],
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='job',
                    name='job_type',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='model.JobType'),
                ),
            ],
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='joblog',
                    name='job',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_log', to='model.Job'),
                ),
            ],
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='textlogstep',
                    name='job',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_log_step', to='model.Job'),
                ),
            ],
        ),
    ]
