# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 20:29
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model", "0011_remove_matcher_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="branch",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
