# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_add_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='model.JobGroup'),
        ),
    ]
