# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_add_job_group_runnable_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='job_group',
        ),
    ]
