# Generated by Django 3.0.2 on 2020-01-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_add_repository_tc_root_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='revision',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
