# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_remove_job_type_group_fk'),
    ]

    # Must make these migrations a DB noop because of this Django Bug:
    # https://code.djangoproject.com/ticket/25253

    operations = [
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='job',
                    name='job_group',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='model.JobGroup'),
                ),
            ],
        ),
    ]
