# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_remove_job_group_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusionprofile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='exclusionprofile',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='jobexclusion',
            name='author',
        ),
        migrations.AlterUniqueTogether(
            name='userexclusionprofile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userexclusionprofile',
            name='exclusion_profile',
        ),
        migrations.RemoveField(
            model_name='userexclusionprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExclusionProfile',
        ),
        migrations.DeleteModel(
            name='JobExclusion',
        ),
        migrations.DeleteModel(
            name='UserExclusionProfile',
        ),
    ]
