# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_remove_exclusion_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlogstep',
            name='result',
            field=models.IntegerField(choices=[(0, 'success'), (1, 'testfailed'), (2, 'busted'), (3, 'skipped'), (4, 'exception'), (5, 'retry'), (6, 'usercancel'), (7, 'unknown'), (8, 'superseded')]),
        ),
    ]
