# Generated by Django 3.0.5 on 2020-05-08 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0017_add_index_task_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDetail',
        ),
    ]
