# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_superseded_to_textlogstep_enum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobduration',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='jobduration',
            name='repository',
        ),
        migrations.DeleteModel(
            name='JobDuration',
        ),
    ]
