# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0019_remove_job_duration'),
    ]
    operations = [
        # Django incorrectly generated:
        #   CREATE INDEX `job_repository_id_20bb4d74` ON `job` (`repository_id`);
        #   ALTER TABLE `job` DROP INDEX `job_repository_id_project_specific_id_7883a5e8_uniq`;
        # We couldn't use manual SQL statements since the index name varies between
        # environments and DROP INDEX doesn't support IF EXISTS. So we'll have to drop manually.
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='job',
                    unique_together=set([]),
                ),
            ]
        )
    ]
