# Generated by Django 3.0.8 on 2020-08-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('model', '0021_testpath'), ('model', '0022_job_test_paths')]

    dependencies = [
        ('model', '0020_textlogerror_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True)),
            ],
            options={'db_table': 'test_path',},
        ),
        migrations.AddField(
            model_name='job', name='test_paths', field=models.ManyToManyField(to='model.TestPath'),
        ),
    ]
