# Generated by Django 3.0.8 on 2020-09-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0020_textlogerror_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigatedTests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=350)),
                (
                    'job_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='investigated',
                        to='model.JobType',
                    ),
                ),
                (
                    'push',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Push'),
                ),
            ],
            options={
                'db_table': 'investigated_tests',
                'unique_together': {('job_type', 'test', 'push')},
            },
        ),
    ]
