# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_remove_project_specific_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='revision',
            field=models.CharField(max_length=40),
        ),
        # The order of the `AlterUniqueTogether` and `RemoveField` has been inverted
        # (compared to the `makemigrations` output), to work around:
        # https://code.djangoproject.com/ticket/29124
        migrations.AlterUniqueTogether(
            name='push',
            unique_together=set([('repository', 'revision')]),
        ),
        migrations.RemoveField(
            model_name='push',
            name='revision_hash',
        ),
    ]
