# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_remove_revision_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugscache',
            name='whiteboard',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bugjobmap',
            name='bug_id',
            field=models.PositiveIntegerField(db_column='bug_id'),
        ),
        migrations.RenameField(
            model_name='bugjobmap',
            old_name='bug_id',
            new_name='bug',
        ),
        migrations.AlterUniqueTogether(
            name='bugjobmap',
            unique_together=set([('job', 'bug')]),
        ),
        migrations.AlterField(
            model_name='bugjobmap',
            name='bug',
            field=models.ForeignKey(on_delete=models.CASCADE, to='model.Bugscache', related_name='bugmap'),
        ),
        migrations.AlterField(
            model_name='push',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
