# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_remove_revision_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugscache',
            name='whiteboard',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='push',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
