# Generated by Django 3.0.8 on 2020-12-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0022_support_group_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='autoclassify_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='coalesced_to_guid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='project_specific_id',
        ),
    ]
