# Generated by Django 3.1.12 on 2021-09-13 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("model", "0024_add_bugzillasecuritygroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugscache",
            name="os",
        ),
    ]
