# Generated by Django 3.1.12 on 2021-09-21 13:51

from datetime import datetime, timedelta

from django.db import migrations, models


def set_update_next_run(apps, schema_editor):
    # Set timestamp of last modification to more than a year ago for all bugs
    # to let them get ingested again on the next run which will populate the
    # 'dupe_of' field for bugs resolved as duplicates with the number of the
    # open bug against which they have been set as duplicate, also resolving
    # chains of duplicates.
    more_than_year_ago = datetime.utcnow() - timedelta(days=400)

    Bugscache = apps.get_model("model", "Bugscache")
    Bugscache.objects.all().update(modified=more_than_year_ago)


class Migration(migrations.Migration):
    dependencies = [
        ("model", "0025_remove_bugscache_os"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugscache",
            name="dupe_of",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bugscache",
            name="processed_update",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_update_next_run),
    ]
