# Generated by Django 4.0.6 on 2022-08-18 12:45

from django.db import migrations, models


def truncate_bugscache(apps, schema_editor):
    Bugscache = apps.get_model('model', 'Bugscache')
    Bugscache.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0028_alter_textlogerror_unique_together'),
    ]

    operations = [
        migrations.RunPython(truncate_bugscache),
        migrations.AddField(
            model_name='bugscache',
            name='created',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
