# Generated by Django 4.1.13 on 2024-03-25 16:15

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0030_group_durations"),
    ]

    operations = [TrigramExtension()]
