# Generated by Django 4.1.13 on 2023-11-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0030_group_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='local_run',
            field=models.TextField(blank=True, default=''),
        ),
    ]
