# Generated by Django 4.1.13 on 2024-05-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0031_trigram_extension"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="failureline",
            new_name="failure_lin_job_gui_b67c6d_idx",
            old_fields=("job_guid", "repository"),
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="job_reposit_f4bb0f_idx",
            old_fields=(
                "repository",
                "build_platform",
                "option_collection_hash",
                "job_type",
                "start_time",
            ),
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="job_reposit_f65dd6_idx",
            old_fields=("repository", "job_type", "start_time"),
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="job_machine_92bdd4_idx",
            old_fields=("machine_platform", "option_collection_hash", "push"),
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="job_reposit_fc1f71_idx",
            old_fields=("repository", "build_platform", "job_type", "start_time"),
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="job_reposit_2101af_idx",
            old_fields=("repository", "submit_time"),
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="job_reposit_63c897_idx",
            old_fields=(
                "repository",
                "option_collection_hash",
                "job_type",
                "start_time",
            ),
        ),
    ]
