# Generated by Django 4.2.13 on 2024-10-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "model",
            "0033_textlogerror_new_failure",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bugjobmap",
            name="bug_open",
            field=models.BooleanField(default=False),
        ),
    ]
