# Generated by Django 5.1.2 on 2024-10-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0033_textlogerror_new_failure"),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="search_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
