# Generated by Django 5.1.1 on 2025-01-10 15:40

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def set_bugzilla_ids(apps, schema_editor):
    Bugscache = apps.get_model("model", "Bugscache")
    Bugscache.objects.all().update(bugzilla_id=F("id"))


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0034_bugjobmap_bug_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugscache",
            name="bugzilla_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            set_bugzilla_ids,
        ),
        migrations.AlterField(
            model_name="bugscache",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="bugscache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bugzilla_id__isnull", False)),
                fields=("bugzilla_id",),
                name="unique_bugzilla_id",
            ),
        ),
        migrations.CreateModel(
            name="BugscacheOccurrence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        to="model.bugscache",
                        related_name="occurrences",
                    ),
                ),
                (
                    "failure_line",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        to="model.failureline",
                        related_name="bug_occurrences",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="BugscacheOccurrence",
            constraint=models.UniqueConstraint(
                fields=("user", "failure_line", "bug"),
                name="unique_failureline_bug_occurrence",
            ),
        ),
    ]
