# Generated by Django 5.1.2 on 2025-01-24 07:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0035_bugscache_optional_bugzilla_ref"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commit",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "revision", "author", "comments", config="english"
                ),
                name="search_vector_idx",
            ),
        ),
    ]
