# Generated by Django 5.1.2 on 2025-02-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0036_bugjobmap_internal_bug_refs"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="textlogerror",
            unique_together={("job", "line_number")},
        ),
        migrations.RemoveField(
            model_name="textlogerror",
            name="step",
        ),
        migrations.DeleteModel(
            name="TextLogStep",
        ),
    ]
