# Generated by Django 5.1.5 on 2025-02-21 16:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0036_bugjobmap_internal_bug_refs"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commit",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "revision", "author", "comments", config="english"
                ),
                name="search_vector_idx",
            ),
        ),
    ]
