# Generated by Django 5.1.5 on 2025-03-06 14:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def update_search_vector(apps, schema_editor):
    Commit = apps.get_model("model", "Commit")
    Commit.objects.update(
        search_vector=SearchVector("revision", "author", "comments", config="english")
    )


class Migration(migrations.Migration):

    replaces = [
        ("model", "0040_remove_commit_search_vector_idx_commit_search_vector_and_more"),
        ("model", "0041_update_search_vector"),
    ]

    dependencies = [
        ("model", "0039_fix_bugscache_autoincrement"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commit",
            name="search_vector_idx",
        ),
        migrations.AddField(
            model_name="commit",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_idx"
            ),
        ),
        migrations.RunPython(update_search_vector),
    ]
