# Generated by Django 5.1.5 on 2025-03-06 14:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.models.functions import Substr


def update_search_vector(apps, schema_editor):
    Commit = apps.get_model("model", "Commit")
    Commit.objects.update(
        search_vector=SearchVector("revision", "author", Substr("comments", 1, 100000), config="english")
    )


class Migration(migrations.Migration):
    dependencies = [
            ("model", "0040_alter_textlogerror_unique_together_and_more"),
        ]

    operations = [
        migrations.RemoveIndex(
            model_name="commit",
            name="search_vector_idx",
        ),
        migrations.AddField(
            model_name="commit",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_idx"
            ),
        ),
        migrations.RunPython(update_search_vector),
    ]
