# Generated by Django 5.1.5 on 2025-03-05 23:46

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def update_search_vector(apps, schema_editor):
    Commit = apps.get_model("model", "Commit")
    Commit.objects.update(
        search_vector=SearchVector("revision", "author", "comments", config="english")
    )
class Migration(migrations.Migration):

    dependencies = [
        ("model", "0040_remove_commit_search_vector_idx_commit_search_vector_and_more"),
    ]

    operations = [
         migrations.RunPython(update_search_vector),
    ]
