# Generated by Django 5.1.8 on 2025-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0041_update_search_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobgroup",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
