# Generated by Django 5.1.11 on 2025-07-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0042_alter_jobgroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedatasignatures",
            name="job_group_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
