# Generated by Django 5.1.11 on 2025-09-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0044_add_optimized_group_results_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failureline",
            name="expected",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASS", "PASS"),
                    ("FAIL", "FAIL"),
                    ("OK", "OK"),
                    ("ERROR", "ERROR"),
                    ("TIMEOUT", "TIMEOUT"),
                    ("CRASH", "CRASH"),
                    ("ASSERT", "ASSERT"),
                    ("SKIP", "SKIP"),
                    ("NOTRUN", "NOTRUN"),
                    ("PRECONDITION_FAILED", "PRECONDITION_FAILED"),
                ],
                max_length=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="failureline",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASS", "PASS"),
                    ("FAIL", "FAIL"),
                    ("OK", "OK"),
                    ("ERROR", "ERROR"),
                    ("TIMEOUT", "TIMEOUT"),
                    ("CRASH", "CRASH"),
                    ("ASSERT", "ASSERT"),
                    ("SKIP", "SKIP"),
                    ("NOTRUN", "NOTRUN"),
                    ("PRECONDITION_FAILED", "PRECONDITION_FAILED"),
                ],
                max_length=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="failureline",
            name="status",
            field=models.CharField(
                choices=[
                    ("PASS", "PASS"),
                    ("FAIL", "FAIL"),
                    ("OK", "OK"),
                    ("ERROR", "ERROR"),
                    ("TIMEOUT", "TIMEOUT"),
                    ("CRASH", "CRASH"),
                    ("ASSERT", "ASSERT"),
                    ("SKIP", "SKIP"),
                    ("NOTRUN", "NOTRUN"),
                    ("PRECONDITION_FAILED", "PRECONDITION_FAILED"),
                ],
                max_length=19,
            ),
        ),
    ]
