# Generated by Django 5.1.14 on 2025-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0046_repository_repo_url_active_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="failureline",
            name="known_intermittent",
            field=models.JSONField(default=list),
        ),
    ]
