# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0047_disallow_null_job_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='project_specific_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
