# Generated by Django 5.1.14 on 2025-12-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0047_failureline_known_intermittent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failureline",
            name="action",
            field=models.CharField(
                choices=[
                    ("test_result", "test_result"),
                    ("log", "log"),
                    ("crash", "crash"),
                    ("truncated", "truncated"),
                    ("group_result", "group_result"),
                    ("test_status", "test_status"),
                    ("test_end", "test_end"),
                ],
                max_length=15,
            ),
        ),
    ]
