# Generated by Django 5.1.15 on 2025-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0048_alter_failureline_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="parsing_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
