# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0048_remove_mandatory_ds_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datasource',
        ),
    ]
