# Generated by Django 5.1.15 on 2025-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0048_alter_failureline_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("exception", "Exception"),
                    ("unscheduled", "Unscheduled"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
