# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0049_remove_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildplatform',
            name='os_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machineplatform',
            name='os_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='optioncollection',
            name='option_collection_hash',
            field=models.CharField(max_length=40),
        ),
    ]
