# Generated by Django 5.1.15 on 2026-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0049_alter_job_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("running", "running"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                    ("exception", "exception"),
                    ("unscheduled", "unscheduled"),
                ],
                max_length=25,
            ),
        ),
    ]
