# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0050_remove_redundant_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
