# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0051_add_job_lastmodified_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='guid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='project_specific_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
