# Generated by Django 6.0.3 on 2026-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0053_push_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="parse_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
