import { getData } from '../helpers/http';
import { getProjectUrl } from '../helpers/location';
import { createQueryParams, pushEndpoint } from '../helpers/url';
import PushModel from '../models/push';

import { rememberHealth, rememberSummary, shared } from './cache';

export const AUTHOR_STORAGE_KEY = 'pushViewAuthor';

export const fetchPushes = (repo, author, count = 15) =>
  getData(
    getProjectUrl(`${pushEndpoint}${createQueryParams({ author, count })}`, repo),
  );

export const fetchPush = (repo, revision) =>
  getData(
    getProjectUrl(`${pushEndpoint}${createQueryParams({ revision })}`, repo),
  );

export const fetchSummary = async (repo, revision) => {
  const { data, failureStatus } = await PushModel.getHealthSummary(
    repo,
    revision,
  );
  const summary = failureStatus || !Array.isArray(data) ? null : data[0];
  if (summary) rememberSummary(repo, revision, summary);
  return summary;
};

// Shared so a fetch started when a finger lands on a list row is the one the
// detail screen picks up, instead of starting over.
export const fetchHealth = (repo, revision) =>
  shared(`health:${repo}:${revision}`, async () => {
    const { data, failureStatus } = await PushModel.getHealth(repo, revision);
    if (failureStatus) return null;
    rememberHealth(repo, revision, data);
    return data;
  });

// A try push's tip commit is generated by `mach try`. When it was given `-m`
// the first line is the human message; otherwise it's try syntax, and the
// author's own words are on the commit underneath.
const isTrySyntax = (line) =>
  /^(Fuzzy query|try:|Try Chooser|Pushed via|Try task config)/i.test(line);

export const pushTitle = (push) => {
  const lines = push.revisions.map((r) => r.comments.split('\n')[0].trim());
  const human = lines.find((line) => line && !isTrySyntax(line));
  if (human) return human;
  // Nothing but try syntax: what was asked for beats a bare hash.
  const query = lines[0]?.match(/^Fuzzy query=(.*)/);
  if (query) return query[1].replace(/&query=/g, ' · ').replace(/[\^$'"]/g, '');
  return push.revision.slice(0, 12);
};

// Job names carry their category as a prefix the section already states.
export const jobShortName = (name) =>
  name.replace(/^source-test-mozlint-/, '').replace(/^source-test-/, '');

const RESULT_WORDS = {
  testfailed: 'failed',
  busted: 'broke',
  exception: 'errored',
  usercancel: 'cancelled',
};

export const resultWord = (result) => RESULT_WORDS[result] || result;

const NUMBER_WORDS = [
  'No',
  'One',
  'Two',
  'Three',
  'Four',
  'Five',
  'Six',
  'Seven',
  'Eight',
  'Nine',
];

export const countWord = (n) => NUMBER_WORDS[n] || String(n);

export const plural = (n, one, many = `${one}s`) => (n === 1 ? one : many);

export const ago = (epochSeconds) => {
  const minutes = Math.max(0, Math.round(Date.now() / 1000 - epochSeconds) / 60);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${Math.round(minutes)}m ago`;
  const hours = minutes / 60;
  if (hours < 24) return `${Math.round(hours)}h ago`;
  const days = Math.round(hours / 24);
  return days === 1 ? 'yesterday' : `${days}d ago`;
};

export const duration = (epochSeconds) => {
  const minutes = Math.round((Date.now() / 1000 - epochSeconds) / 60);
  if (minutes < 60) return `${minutes} min`;
  return `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
};

// `status` counts unclassified, non-tier-3 jobs by state, and completed jobs
// by result. Its own `completed` total can disagree with those per-result
// counts, so finished work is summed from the results.
const NOT_RESULTS = new Set([
  'completed',
  'pending',
  'running',
  'unscheduled',
  'coalesced', // an alias of superseded, kept for old API consumers
]);

export const finishedCount = (status) =>
  Object.entries(status || {})
    .filter(([key]) => !NOT_RESULTS.has(key))
    .reduce((n, [, count]) => n + count, 0);

export const progressOf = (status) => {
  if (!status) return null;
  const done = finishedCount(status);
  // `unscheduled` is tests waiting behind a build: not started, still owed.
  const left =
    (status.pending || 0) + (status.running || 0) + (status.unscheduled || 0);
  return { done, left, total: done + left, running: left > 0 };
};

const clock = (ms) =>
  new Date(ms).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });

const minutesUntil = (ms, now = Date.now()) =>
  Math.max(1, Math.round((ms - now) / 60000));

// "build-linux64-shippable/opt" reads as "linux64 shippable build".
const buildName = (name) =>
  `${name.replace(/^build-/, '').replace(/\/.*$/, '').replace(/-/g, ' ')} build`;

// The ETA in words. Null when the model has nothing honest to say.
export const describeEta = (eta, { started = false, now = Date.now() } = {}) => {
  if (!eta) return null;
  if (eta.confidence === 'firm') {
    const soon = eta.mostAt <= now;
    return {
      headline: soon
        ? 'Most results any minute.'
        : `Most results in ~${minutesUntil(eta.mostAt, now)} min.`,
      line: `Most by ${clock(eta.mostAt)} · all done around ${clock(eta.allAt)}`,
    };
  }
  if (eta.confidence === 'blockedOnBuild' && eta.blockingBuild) {
    const { name, finishAt, blockedJobs } = eta.blockingBuild;
    // Once some of the push has run, it's only the rest that are waiting.
    const who = started ? 'The rest start' : 'Tests start';
    return {
      headline:
        finishAt <= now
          ? `${who} any minute.`
          : `${who} in ~${minutesUntil(finishAt, now)} min.`,
      line: `${blockedJobs} ${blockedJobs === 1 ? 'job waits' : 'jobs wait'} on the ${buildName(name)}`,
    };
  }
  return null;
};

const OS_NAMES = [
  [/^macosx(\d\d)(\d\d)/, (m) => `macOS ${Number(m[1]) === 10 ? `10.${Number(m[2])}` : Number(m[1])}`],
  [/^windows(\d+)/, (m) => `Windows ${m[1]}`],
  [/^win(\d+)/, (m) => `Windows ${m[1]}`],
  [/^linux/, () => 'Linux'],
  [/^android/, () => 'Android'],
];

export const platformName = (platform = '') => {
  const arch = /aarch64|arm64/.test(platform) ? ' ARM' : '';
  for (const [re, name] of OS_NAMES) {
    const m = platform.match(re);
    if (m) return `${name(m)}${arch}`;
  }
  return platform;
};

// "toolkit/content/tests/browser/browser_contentTitle.js" reads as its file
// name first; the directory is context.
export const splitTestPath = (testName) => {
  const i = testName.lastIndexOf('/');
  if (i < 0 || testName.includes('://')) return { dir: '', file: testName };
  return { dir: testName.slice(0, i + 1), file: testName.slice(i + 1) };
};

// Push Health lists one entry per test *per platform and config*. A person
// thinks of "this test broke", so fold those back into one row per test.
export const groupByTest = (failures) => {
  const groups = new Map();
  for (const f of failures) {
    const g = groups.get(f.testName) || {
      testName: f.testName,
      jobIds: new Set(),
      totalJobs: 0,
      platforms: new Set(),
      configs: new Set(),
      failedInParent: true,
      entries: [],
    };
    for (const id of f.failedInJobs) g.jobIds.add(id);
    g.totalJobs += f.totalJobs;
    g.platforms.add(platformName(f.platform));
    g.configs.add(f.config);
    g.failedInParent = g.failedInParent && f.failedInParent;
    g.entries.push(f);
    groups.set(f.testName, g);
  }
  return [...groups.values()].sort((a, b) => b.jobIds.size - a.jobIds.size);
};
