/** Desired capabilities */
def capabilities = [
  browserName: 'Firefox',
  version: '56.0',
  platform: 'Windows 10'
]

pipeline {
  agent any
  libraries {
    lib('fxtest@1.9')
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 1, unit: 'HOURS')
  }
  environment {
    PYTEST_ADDOPTS =
      "--tb=short " +
      "--color=yes " +
      "--driver=SauceLabs " +
      "--variables=capabilities.json"
    PULSE = credentials('PULSE')
    SAUCELABS_API_KEY = credentials('SAUCELABS_API_KEY')
  }
  stages {
    stage('Test') {
      steps {
        writeCapabilities(capabilities, 'tests/jenkins/capabilities.json')
        sh "tox -c tests/jenkins/tox.ini -e py27"
      }
      post {
        always {
          archiveArtifacts 'tests/jenkins/results/*'
          junit 'tests/jenkins/results/*.xml'
          submitToActiveData('tests/jenkins/results/py27_raw.txt')
          submitToTreeherder('treeherder', 'e2e', 'End-to-end integration tests', 'tests/jenkins/results/*', 'tests/jenkins/results/py27_tbpl.txt')
          publishHTML(target: [
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: 'tests/jenkins/results',
            reportFiles: "py27.html",
            reportName: 'HTML Report'])
        }
      }
    }
  }
  post {
    failure {
      mail(
        body: "${BUILD_URL}",
        from: "firefox-test-engineering@mozilla.com",
        replyTo: "firefox-test-engineering@mozilla.com",
        subject: "Build failed in Jenkins: ${JOB_NAME} #${BUILD_NUMBER}",
        to: "fte-ci@mozilla.com")
    }
    changed {
      ircNotification()
    }
  }
}
