test-warnings: false
strictness: medium
max-line-length: 140
uses:
  - django
  - celery
requirements:
  - requirements/common.txt
  - requirements/dev.txt
ignore-paths:
  - .git
  - bin/peep.py
  - deployment/update/update.py
  - docs
# We run flake8 (pep8 + pyflakes) as part of the Travis run,
# so it's unnecessary to run them again here.
pep8:
  run: false
pyflakes:
  run: false
