# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2
build:
  image: latest
python:
  version: 3.10
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
mkdocs:
  configuration: mkdocs.yml
