# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
mkdocs:
  configuration: mkdocs.yml
