[mozci]
verbose = 1
data_sources = ['treeherder_db', 'hgmo', 'taskcluster']
maxdepth=1

[mozci.cache]
default = "file"
retention = 40320
serializer = "compressedpickle"

[mozci.cache.stores]
file = { driver = "file", path = "mozci_tests_cache" }
