docs_dir: 'docs'
site_dir: '.build-docs'
strict: true
use_directory_urls: false

site_name: 'Treeherder Docs'
site_url: 'https://treeherder.readthedocs.io'
repo_name: 'mozilla/treeherder'
repo_url: 'https://github.com/mozilla/treeherder'

# https://squidfunk.github.io/mkdocs-material/getting-started/#configuration
theme:
  name: 'material'

# https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # Fixes fenced code blocks within lists.
  - 'pymdownx.superfences':
      disable_indented_code_blocks: True
  # Allows index.md to include the repo root README.
  - 'pymdownx.snippets':
      check_paths: True
  # Required so that 2 space indents within lists work the same as
  # GitHub and Prettier's markdown implementation.
  - mdx_truly_sane_lists

# http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - About: 'index.md'
  - Development:
      - Installation: 'installation.md'
      - Testing: 'testing.md'
      - Loading Pulse data: 'pulseload.md'
      - Code Style: 'code_style.md'
      - Accessibility: 'accessibility.md'
      - Common tasks: 'common_tasks.md'
      - Backend tasks: 'backend_tasks.md'
  - Infrastructure:
      - Architecture: 'infrastructure/architecture.md'
      - Administration: 'infrastructure/administration.md'
      - Troubleshooting: 'infrastructure/troubleshooting.md'
  - Accessing data: 'accessing_data.md'
  - Submitting data: 'submitting_data.md'
  - SETA: 'seta.md'
  - Manual test cases: 'testcases.md'
