# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrequest',
            name='repository',
        ),
        migrations.DeleteModel(
            name='TaskRequest',
        ),
    ]
