# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seta', '0002_remove_task_request_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpriority',
            name='timeout',
        ),
    ]
