WHITEBOARD_NEEDSWORK_OWNER = "[stockwell needswork:owner]"

COMPONENTS = [
    ["Core", "Canvas: 2D"],
    ["Core", "Canvas: WebGL"],
    ["Core", "DOM"],
    ["Core", "DOM: Core & HTML"],
    ["Core", "DOM: Device Interfaces"],
    ["Core", "DOM: Events"],
    ["Core", "DOM: IndexedDB"],
    ["Core", "DOM: Push Notifications"],
    ["Core", "DOM: Quota Manager"],
    ["Core", "DOM: Service Workers"],
    ["Core", "DOM: Workers"],
    ["Core", "DOM:Content Processes"],
    ["Core", "Document Navigation"],
    ["Core", "Event Handling"],
    ["Core", "GFX: Color Management"],
    ["Core", "Graphics"],
    ["Core", "Graphics: Layers"],
    ["Core", "Graphics: Text"],
    ["Core", "Graphics: WebRender"],
    ["Core", "HTML: Form Submission"],
    ["Core", "HTML: Parser"],
    ["Core", "IPC"],
    ["Core", "Image Blocking"],
    ["Core", "ImageLib"],
    ["Core", "Javascript Engine"],
    ["Core", "Javascript Engine: JIT"],
    ["Core", "Javascript: GC"],
    ["Core", "Javascript: Internationalization API"],
    ["Core", "Javascript: Standard Library"],
    ["Core", "Keyboard: Navigation"],
    ["Core", "Networking"],
    ["Core", "Networking: Cache"],
    ["Core", "Networking: Cookies"],
    ["Core", "Networking: DNS"],
    ["Core", "Networking: Domain Lists"],
    ["Core", "Networking: FTP"],
    ["Core", "Networking: File"],
    ["Core", "Networking: HTTP"],
    ["Core", "Networking: JAR"],
    ["Core", "Networking: WebSockets"],
    ["Core", "Plug-ins"],
    ["Core", "Security: Sandboxing Process"],
    ["Core", "Serializers"],
    ["Core", "Widget"],
    ["Core", "Widget: Win32"],
    ["Core", "Widget: WinRT"],
    ["Core", "XBL"],
    ["Core", "XML"],
    ["Core", "XPConnect"],
    ["Core", "XSLT"],
    ["Core", "js-ctypes"],
    ["Firefox for Android", "Add-ons Manager"],
    ["Firefox for Android", "Testing"],
    ["Firefox", "Disability Access"],
    ["Firefox", "Toolbars and Customization"],
    ["Toolkit", "Add-ons Manager"],
    ["Toolkit", "Reader Mode"],
    ["Toolkit", "Toolbars and Toolbar Customization"],
    ["Toolkit", "WebExtensions: Android"],
    ["Toolkit", "WebExtensions: Android"],
    ["Toolkit", "WebExtensions: Compatibility"],
    ["Toolkit", "WebExtensions: Developer Tools"],
    ["Toolkit", "WebExtensions: Experiments"],
    ["Toolkit", "WebExtensions: Frontend"],
    ["Toolkit", "WebExtensions: General"],
    ["Toolkit", "WebExtensions: Request Handling"],
    ["Toolkit", "WebExtensions: Untriaged"],
]
