from django.core.management.base import BaseCommand
from treeherder.etl import buildapi


class Command(BaseCommand):
    """Management command to run mozilla pulse consumer."""

    help = (
        "Tests the buildernames and data structures in the builds4h.js"
        "generated by buildbot"
    )

    def handle(self, *args, **options):

        ba = buildapi.Builds4hAnalyzer()
        ba.run()

