# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:50
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        (b'perf', '0001_initial'),
        (b'perf', '0002_auto_20151014_0922'),
        (b'perf', '0003_performancesignature_lower_is_better'),
        (b'perf', '0004_auto_20151116_1041'),
        (b'perf', '0005_auto_20151124_1051'),
        (b'perf', '0006_add_perfalerts_revised_summary'),
        (b'perf', '0007_alert_status'),
        (b'perf', '0008_delete_perfalerts'),
        (b'perf', '0009_refactor_perfalerts'),
        (b'perf', '0010_add_alertsummary_backed_out'),
        (b'perf', '0011_remove_null_fields_after_migration'),
        (b'perf', '0012_performancesignature_parent_signature'),
        (b'perf', '0013_add_has_subtests_property'),
        (b'perf', '0014_allow_same_signature_hash_different_frameworks'),
        (b'perf', '0015_make_alerting_configurable_per_series'),
        (b'perf', '0016_manually_created_alerts'),
        (b'perf', '0017_performancebugtemplate'),
        (b'perf', '0017_add_performanceframework_enabled'),
        (b'perf', '0018_merge'),
        (b'perf', '0019_performancealert_classifier'),
        (b'perf', '0020_remove_useless_perf_indexes'),
        (b'perf', '0021_push_and_commit_orm'),
        (b'perf', '0022_alert_summary_push_uniqueness'),
        (b'perf', '0023_push_and_commit_orm_2'),
        (b'perf', '0024_rename_ds_job_id_column'),
        (b'perf', '0025_rename_orm_property'),
        (b'perf', '0026_drop_alertsummary_rsid'),
        (b'perf', '0027_add_job_fk_reference_perfdatum'),
        (b'perf', '0028_framework_mandatory_perf_alert_summary'),
        (b'perf', '0029_remove_mandatory_ds_ids'),
        (b'perf', '0030_performancesignature_extra_options'),
        (b'perf', '0031_remove_performancesignature_extra_properties'),
        (b'perf', '0032_remove_redundant_indexes'),
    ]

    initial = True

    dependencies = [
        ('model', '0046_remove_flat_exclusion_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0001_initial'),
        ('model', '0003_auto_20151111_0942'),
        ('model', '0039_push_and_commit_orm'),
        ('model', '0002_auto_20151014_0900'),
        ('model', '0050_remove_redundant_indexes'),
        ('model', '0008__add_best_fields_to_failureline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_regression', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, b'Untriaged'), (1, b'Downstream'), (2, b'Reassigned'), (3, b'Invalid'), (4, b'Acknowledged')], default=0)),
                ('amount_pct', models.FloatField(help_text=b'Amount in percentage that series has changed')),
                ('amount_abs', models.FloatField(help_text=b'Absolute amount that series has changed')),
                ('prev_value', models.FloatField(help_text=b'Previous value of series before change')),
                ('new_value', models.FloatField(help_text=b'New value of series after change')),
                ('t_value', models.FloatField(help_text=b"t value out of analysis indicating confidence that change is 'real'", null=True)),
                ('manually_created', models.BooleanField(default=False)),
                ('classifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_alert',
            },
        ),
        migrations.CreateModel(
            name='PerformanceAlertSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manually_created', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(db_index=True)),
                ('status', models.IntegerField(choices=[(0, b'Untriaged'), (1, b'Downstream'), (3, b'Invalid'), (4, b'Improvement'), (5, b'Investigating'), (6, b"Won't fix"), (7, b'Fixed'), (8, b'Backed out')], default=0)),
                ('bug_number', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'performance_alert_summary',
            },
        ),
        migrations.CreateModel(
            name='PerformanceBugTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('status_whiteboard', models.CharField(max_length=255)),
                ('default_component', models.CharField(max_length=255)),
                ('default_product', models.CharField(max_length=255)),
                ('cc_list', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=4096)),
            ],
            options={
                'db_table': 'performance_bug_template',
            },
        ),
        migrations.CreateModel(
            name='PerformanceDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('push_timestamp', models.DateTimeField()),
                ('ds_job_id', models.PositiveIntegerField(db_column=b'ds_job_id', null=True)),
                ('result_set_id', models.PositiveIntegerField(null=True)),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.Job')),
                ('push', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Push')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Repository')),
            ],
            options={
                'db_table': 'performance_datum',
            },
        ),
        migrations.CreateModel(
            name='PerformanceFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'performance_framework',
            },
        ),
        migrations.CreateModel(
            name='PerformanceSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_hash', models.CharField(db_index=True, max_length=40, validators=[django.core.validators.MinLengthValidator(40)])),
                ('suite', models.CharField(max_length=80)),
                ('test', models.CharField(blank=True, max_length=80)),
                ('lower_is_better', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(db_index=True)),
                ('has_subtests', models.BooleanField()),
                ('extra_options', models.CharField(blank=True, max_length=60)),
                ('should_alert', models.NullBooleanField()),
                ('alert_threshold', models.FloatField(null=True)),
                ('min_back_window', models.IntegerField(null=True)),
                ('max_back_window', models.IntegerField(null=True)),
                ('fore_window', models.IntegerField(null=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.PerformanceFramework')),
                ('option_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.OptionCollection')),
                ('parent_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtests', to='perf.PerformanceSignature')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.MachinePlatform')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Repository')),
            ],
            options={
                'db_table': 'performance_signature',
            },
        ),
        migrations.AddField(
            model_name='performancedatum',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.PerformanceSignature'),
        ),
        migrations.AddField(
            model_name='performancebugtemplate',
            name='framework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perf.PerformanceFramework'),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.PerformanceFramework'),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='prev_push',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='model.Push'),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='push',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='model.Push'),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Repository'),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='related_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_alerts', to='perf.PerformanceAlertSummary'),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='series_signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.PerformanceSignature'),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='perf.PerformanceAlertSummary'),
        ),
        migrations.AlterUniqueTogether(
            name='performancesignature',
            unique_together=set([('repository', 'framework', 'signature_hash')]),
        ),
        migrations.AlterUniqueTogether(
            name='performancedatum',
            unique_together=set([('repository', 'job', 'push', 'signature')]),
        ),
        migrations.AlterIndexTogether(
            name='performancedatum',
            index_together=set([('repository', 'signature', 'push_timestamp')]),
        ),
        migrations.AlterUniqueTogether(
            name='performancealertsummary',
            unique_together=set([('repository', 'framework', 'prev_push', 'push')]),
        ),
        migrations.AlterUniqueTogether(
            name='performancealert',
            unique_together=set([('summary', 'series_signature')]),
        ),
    ]
