# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_squashed_0032_remove_redundant_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancesignature',
            name='signature_hash',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(40)]),
        ),
    ]
