# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0002_remove_signature_hash_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesignature',
            name='alert_change_type',
            field=models.IntegerField(choices=[(0, b'percentage'), (1, b'absolute')], null=True),
        ),
    ]
