# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0004_add_per_push_performance_datum_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('task_base_url', models.URLField(max_length=512)),
                ('main_url', models.URLField(max_length=512)),
            ],
            options={
                'db_table': 'issue_tracker',
            },
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='issue_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perf.IssueTracker'),
        ),
    ]
