# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 08:41
from __future__ import unicode_literals

from django.db import migrations


def set_perfstrip_threshold(apps, schema_editor):
    PerformanceSignature = apps.get_model('perf', 'PerformanceSignature')
    for signature in PerformanceSignature.objects.all():
        if signature.suite == 'Strings' and 'PerfStrip' in signature.test:
            signature.alert_threshold = 8
            signature.save()


def unset_perfstrip_theshold(apps, schema_editor):
    PerformanceSignature = apps.get_model('perf', 'PerformanceSignature')
    for signature in PerformanceSignature.objects.all():
        if signature.suite == 'Strings' and 'PerfStrip' in signature.test:
            signature.alert_threshold = None
            signature.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0004_add_per_push_performance_datum_index'),
    ]

    operations = [
        migrations.RunPython(set_perfstrip_threshold,
                             reverse_code=unset_perfstrip_theshold)
    ]
