# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 14:53
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perf", "0001_squashed_0005_permit_github_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealertsummary",
            name="notes",
            field=models.TextField(null=True, blank=True),
        ),
    ]
