# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 09:25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0006_add_alert_summary_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancealert', name='starred', field=models.BooleanField(default=False),
        ),
    ]
