# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 08:20
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perf", "0010_fix_signature_uniqueness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancesignature",
            name="extra_options",
            field=models.CharField(blank=True, max_length=360),
        ),
    ]
