# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 15:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0011_inc_extra_options_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancealertsummary', old_name='last_updated', new_name='created',
        ),
    ]
