# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-22 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0012_rename_summary_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancealert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancealert',
            name='first_triaged',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='first_triaged',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='performancealertsummary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
