# Generated by Django 2.0.13 on 2019-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0012_rename_summary_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancealert', name='created', field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='performancealert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='first_triaged',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='performancealert',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancealertsummary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='first_triaged',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='performancealertsummary',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='performancealertsummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
