# Generated by Django 2.1.7 on 2019-03-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_add_job_log_status_skipped_size'),
        ('perf', '0013_add_alert_timestamps'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='performancedatum',
            index_together={('push_timestamp',), ('repository', 'signature', 'push_timestamp'), ('repository', 'signature', 'push')},
        ),
    ]
