# Generated by Django 2.2.1 on 2019-05-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0015_add_bug_updated_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancealertsummary',
            name='status',
            field=models.IntegerField(
                choices=[
                    (0, 'Untriaged'),
                    (1, 'Downstream'),
                    (2, 'Reassigned'),
                    (3, 'Invalid'),
                    (4, 'Improvement'),
                    (5, 'Investigating'),
                    (6, "Won't fix"),
                    (7, 'Fixed'),
                    (8, 'Backed out'),
                    (9, 'Confirming'),
                ],
                default=0,
            ),
        ),
    ]
