# Generated by Django 2.2.4 on 2019-08-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0016_modify_alertsummary_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedatum',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
