# Generated by Django 2.2.4 on 2019-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0017_assignment_support_for_alert_summaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancealert',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'Untriaged'), (1, 'Downstream'), (2, 'Reassigned'), (3, 'Invalid'), (4, 'Acknowledged')],
                default=0),
        ),
        migrations.AlterField(
            model_name='performancealertsummary',
            name='status',
            field=models.IntegerField(choices=[(0, 'Untriaged'), (1, 'Downstream'), (2, 'Reassigned'), (3, 'Invalid'), (4, 'Improvement'), (5, 'Investigating'), (6, "Won't fix"), (7, 'Fixed'), (8, 'Backed out')], default=0),
        ),
    ]
