# Generated by Django 2.2.6 on 2019-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perf", "0022_add_test_display_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancesignature",
            name="extra_options",
            field=models.CharField(blank=True, max_length=422),
        ),
    ]
