# Generated by Django 2.2.6 on 2019-11-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0023_increase_extra_options_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillReport',
            fields=[
                (
                    'summary',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='backfill_report',
                        serialize=False,
                        to='perf.PerformanceAlertSummary',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'backfill_report',},
        ),
        migrations.CreateModel(
            name='BackfillRecord',
            fields=[
                (
                    'alert',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='backfill_record',
                        serialize=False,
                        to='perf.PerformanceAlert',
                    ),
                ),
                ('context', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='records',
                        to='perf.BackfillReport',
                    ),
                ),
            ],
            options={'db_table': 'backfill_record',},
        ),
    ]
