# Generated by Django 2.2.6 on 2019-11-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('perf', '0024_support_backfill_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesignature',
            name='tags',
            field=models.CharField(blank=True, max_length=360),
        ),
    ]
