# Generated by Django 3.0.3 on 2020-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0026_add_backfill_record_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('settings', models.TextField()),
            ],
            options={
                'db_table': 'performance_settings',
            },
        ),
    ]
