# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0027_add_job_fk_reference_perfdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancealertsummary',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.PerformanceFramework'),
        ),
    ]
