# Generated by Django 3.0.3 on 2020-03-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0028_default_application_to_empty_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='backfillreport', name='frozen', field=models.BooleanField(default=False),
        ),
    ]
