# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0028_framework_mandatory_perf_alert_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedatum',
            name='ds_job_id',
            field=models.PositiveIntegerField(db_column=b'ds_job_id', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='performancedatum',
            unique_together=set([('repository', 'job', 'push', 'signature')]),
        ),
        migrations.AlterIndexTogether(
            name='performancedatum',
            index_together=set([('repository', 'signature', 'push_timestamp'), ('repository', 'job')]),
        ),
    ]
