# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0029_remove_mandatory_ds_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesignature',
            name='extra_options',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
