# Generated by Django 3.0.4 on 2020-04-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_add_index_commit_revision'),
        ('perf', '0029_add_frozen_to_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancesignature',
            unique_together={
                (
                    'repository',
                    'suite',
                    'test',
                    'framework',
                    'platform',
                    'option_collection',
                    'extra_options',
                    'last_updated',
                    'application',
                ),
                ('repository', 'framework', 'signature_hash'),
                (
                    'repository',
                    'suite_public_name',
                    'test_public_name',
                    'framework',
                    'platform',
                    'option_collection',
                    'extra_options',
                ),
            },
        ),
    ]
