# Generated by Django 3.0.5 on 2020-04-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_add_index_commit_revision'),
        ('perf', '0030_add_application_to_contraints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancesignature',
            unique_together={('repository', 'framework', 'application', 'signature_hash'), ('repository', 'suite', 'test', 'framework', 'platform', 'option_collection', 'extra_options', 'last_updated', 'application'), ('repository', 'suite_public_name', 'test_public_name', 'framework', 'platform', 'option_collection', 'extra_options')},
        ),
    ]
