# Generated by Django 3.0.5 on 2020-04-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0030_add_application_to_contraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('model', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('chunk_size', models.IntegerField(default=100)),
                ('count', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='performancedatum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
