# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0030_performancesignature_extra_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancesignature',
            name='extra_properties',
        ),
    ]
