# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0050_remove_redundant_indexes'),
        ('perf', '0031_remove_performancesignature_extra_properties'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='performancedatum',
            index_together=set([('repository', 'signature', 'push_timestamp')]),
        ),
    ]
