# Generated by Django 3.0.5 on 2020-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perf", "0031_fix_application_in_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "alert_summaries",
                    models.ManyToManyField(
                        related_name="performance_tags", to="perf.PerformanceAlertSummary"
                    ),
                ),
            ],
            options={
                "db_table": "performance_tag",
            },
        ),
    ]
