# Generated by Django 3.0.8 on 2020-08-26 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0020_textlogerror_job'),
        ('perf', '0032_add_performance_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiCommitDatum',
            fields=[
                (
                    'perf_datum',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='multi_commit_datum',
                        serialize=False,
                        to='perf.PerformanceDatum',
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='performancedatum',
            unique_together={('repository', 'job', 'push', 'push_timestamp', 'signature')},
        ),
    ]
