# Generated by Django 3.0.8 on 2020-12-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0034_remove_performancedatum_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multicommitdatum',
            old_name='perf_datum',
            new_name='id',
        ),
        migrations.AddField(
            model_name='multicommitdatum',
            name='perf_datum',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='perf.PerformanceDatum'
            ),
        ),
        migrations.AlterField(
            model_name='multicommitdatum',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='multicommitdatum',
            name='perf_datum',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='multi_commit_datum',
                to='perf.PerformanceDatum',
            ),
        ),
    ]
