# Generated by Django 3.1.4 on 2020-12-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perf", "0034_remove_performancedatum_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancesignature",
            name="should_alert",
            field=models.BooleanField(null=True),
        ),
    ]
