# Generated by Django 3.1.4 on 2021-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('perf', '0037_extend_backfill_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backfillrecord',
            name='status',
            field=models.IntegerField(
                choices=[
                    (0, 'Preliminary'),
                    (1, 'Ready for processing'),
                    (2, 'Backfilled'),
                    (3, 'Successful'),
                    (4, 'Failed'),
                ],
                default=0,
            ),
        ),
    ]
