# Generated by Django 3.1.6 on 2021-04-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0022_support_group_status'),
        ('perf', '0038_update_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backfillrecord',
            name='job_group',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='backfill_records',
                to='model.jobgroup',
            ),
        ),
        migrations.AddField(
            model_name='backfillrecord',
            name='job_tier',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
