# Generated by Django 3.1.8 on 2021-06-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0039_store_more_job_details_on_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancealert',
            name='noise_profile',
            field=models.CharField(default='N/A', help_text='The noise profile of the data which precedes this alert.', max_length=30),
        ),
    ]
