# Generated by Django 3.1.12 on 2021-12-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0041_backfillnotificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedatum',
            name='replicates',
            field=models.TextField(default=None),
        ),
    ]
