# Generated by Django 3.1.13 on 2021-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0041_backfillnotificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='backfillrecord',
            name='total_backfills_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backfillrecord',
            name='total_backfills_in_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backfillrecord',
            name='total_backfills_successful',
            field=models.IntegerField(default=0),
        ),
    ]
