# Generated by Django 3.1.14 on 2022-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Update the PerformanceDatum table to use a bigint for the primary key.
    Please ensure the new table has been filled with the `perf_datum_pk_migration` command for better performance.
    """

    dependencies = [
        ('perf', '0043_perf_datum_bigint_table'),
    ]

    operations = [
        # There is no need to lock the table as the Django migration will be performed in a transaction
        migrations.RunSQL(
            [
                # Copy last performance_datum table entries
                (
                    'INSERT INTO performance_datum_new SELECT * FROM performance_datum '
                    'WHERE `performance_datum`.`id` > (SELECT MAX(id) FROM performance_datum_new)'
                ),
                (
                    'RENAME TABLE performance_datum TO performance_datum_old, '
                    'performance_datum_new TO performance_datum'
                ),
                'DROP TABLE performance_datum_old',
            ],
            reverse_sql=migrations.RunSQL.noop,
            elidable=False,
            state_operations=[
                migrations.AlterField(
                    model_name='performancedatum',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
