# Generated by Django 3.2.13 on 2022-05-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0046_restore_cascade_perf_datum_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancealertsummary',
            name='triage_due_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
