# Generated by Django 4.0.8 on 2023-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perf", "0047_performancealertsummary_triage_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancedatum",
            name="application_version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
