# Generated by Django 4.2.5 on 2023-09-19 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('perf', '0050_cascade_perf_datum_deletion_replicate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='performancedatum',
            new_name='performance_reposit_c9d328_idx',
            old_fields=('repository', 'signature', 'push_timestamp'),
        ),
        migrations.RenameIndex(
            model_name='performancedatum',
            new_name='performance_reposit_5486e2_idx',
            old_fields=('repository', 'signature', 'push'),
        ),
    ]
