# Generated by Django 4.0.8 on 2023-03-28 09:33

from django.db import migrations, models

from treeherder.perf.utils import BUG_DAYS, calculate_time_to


def update_summary_bug_due_date(apps, schema_editor):
    PerformanceAlertSummary = apps.get_model('perf', 'PerformanceAlertSummary')

    for row in PerformanceAlertSummary.objects.all():
        row.bug_due_date = calculate_time_to(row.created, due_days=BUG_DAYS)
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('perf', '0050_cascade_perf_datum_deletion_replicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancealertsummary',
            name='bug_due_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.RunPython(
            update_summary_bug_due_date,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
