# Generated by Django 4.1.13 on 2024-05-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0051_performancealertsummary_bug_due_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="performancedatum",
            new_name="performance_reposit_c9d328_idx",
            old_fields=("repository", "signature", "push_timestamp"),
        ),
        migrations.RenameIndex(
            model_name="performancedatum",
            new_name="performance_reposit_5486e2_idx",
            old_fields=("repository", "signature", "push"),
        ),
    ]
