# Generated by Django 4.2.16 on 2024-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0053_performancealertsummarytesting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealert",
            name="confidence",
            field=models.FloatField(
                help_text="A value that indicates the confidence of the alert (specific to the detection method used)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="detection_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="performancealerttesting",
            name="confidence",
            field=models.FloatField(
                help_text="A value that indicates the confidence of the alert (specific to the detection method used)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="performancealerttesting",
            name="detection_method",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
