# Generated by Django 5.1.3 on 2024-11-13 12:14

import django.db.models.deletion
from django.db import migrations, models


def update_summary_original_push(apps, schema_editor):
    PerformanceAlertSummary = apps.get_model('perf', 'PerformanceAlertSummary')
    for alert in PerformanceAlertSummary.objects.all():
        alert.original_push = alert.push
        alert.save()


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0055_remove_performancealerttesting_related_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealertsummary",
            name="original_push",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                null=True,
                default=None,
                to="model.push",
            ),
        ),
        migrations.RunPython(update_summary_original_push, reverse_code=migrations.RunPython.noop),
    ]
