# Generated by Django 5.1.4 on 2025-01-31 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0035_bugscache_optional_bugzilla_ref"),
        ("perf", "0056_performancealertsummary_original_push"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealert",
            name="confidence",
            field=models.FloatField(
                help_text="A value that indicates the confidence of the alert (specific to the detection method used)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="detection_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="PerformanceAlertSummaryTesting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("manually_created", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("triage_due_date", models.DateTimeField(default=None, null=True)),
                ("first_triaged", models.DateTimeField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Untriaged"),
                            (1, "Downstream"),
                            (2, "Reassigned"),
                            (3, "Invalid"),
                            (4, "Improvement"),
                            (5, "Investigating"),
                            (6, "Won't fix"),
                            (7, "Fixed"),
                            (8, "Backed out"),
                        ],
                        default=0,
                    ),
                ),
                ("bug_number", models.PositiveIntegerField(null=True)),
                ("bug_due_date", models.DateTimeField(default=None, null=True)),
                ("bug_updated", models.DateTimeField(null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_alerts_testing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perf.performanceframework",
                    ),
                ),
                (
                    "issue_tracker",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="perf.issuetracker",
                    ),
                ),
                (
                    "original_push",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "prev_push",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "push",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model.repository",
                    ),
                ),
            ],
            options={
                "db_table": "performance_alert_summary_testing",
                "unique_together": {("repository", "framework", "prev_push", "push")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceTelemetryAlertSummary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("manually_created", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("triage_due_date", models.DateTimeField(default=None, null=True)),
                ("first_triaged", models.DateTimeField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Untriaged"),
                            (1, "Downstream"),
                            (2, "Reassigned"),
                            (3, "Invalid"),
                            (4, "Improvement"),
                            (5, "Investigating"),
                            (6, "Won't fix"),
                            (7, "Fixed"),
                            (8, "Backed out"),
                        ],
                        default=0,
                    ),
                ),
                ("bug_number", models.PositiveIntegerField(null=True)),
                ("bug_due_date", models.DateTimeField(default=None, null=True)),
                ("bug_updated", models.DateTimeField(null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_telemetry_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perf.performanceframework",
                    ),
                ),
                (
                    "issue_tracker",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="perf.issuetracker",
                    ),
                ),
                (
                    "original_push",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "prev_push",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "push",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model.repository",
                    ),
                ),
            ],
            options={
                "db_table": "performance_telemetry_alert_summary",
                "unique_together": {("repository", "framework", "prev_push", "push")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceTelemetrySignature",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("Nightly", "Mozilla-central Builds"),
                            ("Beta", "Mozilla-beta Builds"),
                            ("Release", "Mozilla-release Builds"),
                        ],
                        max_length=30,
                    ),
                ),
                ("platform", models.CharField(max_length=80)),
                ("probe", models.CharField(max_length=80)),
                (
                    "probe_type",
                    models.CharField(
                        choices=[
                            (
                                "Glean",
                                "Probes that are from the Glean Telemetry System",
                            ),
                            (
                                "Legacy",
                                "Probes that are from the Legacy Telemetry System",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        default="",
                        help_text="Application that runs the signature's tests. Generally used to record browser's name, but not necessarily.",
                        max_length=80,
                    ),
                ),
            ],
            options={
                "db_table": "performance_telemetry_signature",
                "unique_together": {
                    ("channel", "probe", "probe_type", "platform", "application")
                },
            },
        ),
        migrations.CreateModel(
            name="PerformanceTelemetryAlert",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_regression", models.BooleanField()),
                ("starred", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("first_triaged", models.DateTimeField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Untriaged"),
                            (1, "Downstream"),
                            (2, "Reassigned"),
                            (3, "Invalid"),
                            (4, "Acknowledged"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "amount_pct",
                    models.FloatField(
                        help_text="Amount in percentage that series has changed"
                    ),
                ),
                (
                    "amount_abs",
                    models.FloatField(
                        help_text="Absolute amount that series has changed"
                    ),
                ),
                (
                    "prev_value",
                    models.FloatField(
                        help_text="Previous value of series before change"
                    ),
                ),
                (
                    "new_value",
                    models.FloatField(help_text="New value of series after change"),
                ),
                (
                    "t_value",
                    models.FloatField(
                        help_text="t value out of analysis indicating confidence that change is 'real'",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="A value that indicates the confidence of the alert (specific to the detection method used)",
                        null=True,
                    ),
                ),
                ("detection_method", models.CharField(max_length=100, null=True)),
                (
                    "noise_profile",
                    models.CharField(
                        choices=[
                            (
                                "SKEWED",
                                "Samples are heavily found on one side of the mean.",
                            ),
                            (
                                "OUTLIERS",
                                "There are more outliers than should be expected from a normal distribution.",
                            ),
                            (
                                "MODAL",
                                "There are multiple areas where most values are found rather than only one.",
                            ),
                            ("OK", "No issues were found."),
                            ("N/A", "Could not compute a noise profile."),
                        ],
                        default="N/A",
                        help_text="The noise profile of the data which precedes this alert.",
                        max_length=30,
                    ),
                ),
                ("manually_created", models.BooleanField(default=False)),
                ("sustained", models.BooleanField(default=False)),
                ("direction", models.CharField(max_length=100, null=True)),
                (
                    "prev_median",
                    models.FloatField(
                        help_text="Previous median value of series before change"
                    ),
                ),
                (
                    "new_median",
                    models.FloatField(
                        help_text="New median value of series after change"
                    ),
                ),
                (
                    "prev_p90",
                    models.FloatField(
                        help_text="Previous P90 value of series before change"
                    ),
                ),
                (
                    "new_p90",
                    models.FloatField(help_text="New P90 value of series after change"),
                ),
                (
                    "prev_p95",
                    models.FloatField(
                        help_text="Previous P95 value of series before change"
                    ),
                ),
                (
                    "new_p95",
                    models.FloatField(help_text="New P95 value of series after change"),
                ),
                (
                    "classifier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_summary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_alerts",
                        to="perf.performancetelemetryalertsummary",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="perf.performancetelemetryalertsummary",
                    ),
                ),
                (
                    "series_signature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perf.performancetelemetrysignature",
                    ),
                ),
            ],
            options={
                "db_table": "performance_telemetry_alert",
                "unique_together": {("summary", "series_signature")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceAlertTesting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_regression", models.BooleanField()),
                ("starred", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("first_triaged", models.DateTimeField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Untriaged"),
                            (1, "Downstream"),
                            (2, "Reassigned"),
                            (3, "Invalid"),
                            (4, "Acknowledged"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "amount_pct",
                    models.FloatField(
                        help_text="Amount in percentage that series has changed"
                    ),
                ),
                (
                    "amount_abs",
                    models.FloatField(
                        help_text="Absolute amount that series has changed"
                    ),
                ),
                (
                    "prev_value",
                    models.FloatField(
                        help_text="Previous value of series before change"
                    ),
                ),
                (
                    "new_value",
                    models.FloatField(help_text="New value of series after change"),
                ),
                (
                    "t_value",
                    models.FloatField(
                        help_text="t value out of analysis indicating confidence that change is 'real'",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="A value that indicates the confidence of the alert (specific to the detection method used)",
                        null=True,
                    ),
                ),
                ("detection_method", models.CharField(max_length=100, null=True)),
                (
                    "noise_profile",
                    models.CharField(
                        choices=[
                            (
                                "SKEWED",
                                "Samples are heavily found on one side of the mean.",
                            ),
                            (
                                "OUTLIERS",
                                "There are more outliers than should be expected from a normal distribution.",
                            ),
                            (
                                "MODAL",
                                "There are multiple areas where most values are found rather than only one.",
                            ),
                            ("OK", "No issues were found."),
                            ("N/A", "Could not compute a noise profile."),
                        ],
                        default="N/A",
                        help_text="The noise profile of the data which precedes this alert.",
                        max_length=30,
                    ),
                ),
                ("manually_created", models.BooleanField(default=False)),
                ("sustained", models.BooleanField(default=False)),
                ("direction", models.CharField(max_length=100, null=True)),
                (
                    "prev_median",
                    models.FloatField(
                        help_text="Previous median value of series before change"
                    ),
                ),
                (
                    "new_median",
                    models.FloatField(
                        help_text="New median value of series after change"
                    ),
                ),
                (
                    "prev_p90",
                    models.FloatField(
                        help_text="Previous P90 value of series before change"
                    ),
                ),
                (
                    "new_p90",
                    models.FloatField(help_text="New P90 value of series after change"),
                ),
                (
                    "prev_p95",
                    models.FloatField(
                        help_text="Previous P95 value of series before change"
                    ),
                ),
                (
                    "new_p95",
                    models.FloatField(help_text="New P95 value of series after change"),
                ),
                (
                    "classifier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_summary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_alerts",
                        to="perf.performancealertsummarytesting",
                    ),
                ),
                (
                    "series_signature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perf.performancesignature",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="perf.performancealertsummarytesting",
                    ),
                ),
                (
                    "telemetry_series_signature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perf.performancetelemetrysignature",
                    ),
                ),
            ],
            options={
                "db_table": "performance_alert_testing",
                "unique_together": {
                    ("summary", "series_signature"),
                    ("summary", "telemetry_series_signature"),
                },
            },
        ),
    ]
