# Generated by Django 5.1.4 on 2025-03-26 17:29

import django.db.models.deletion
from django.db import migrations, models


def update_summary_original_push(apps, schema_editor):
    performancealertsummary = apps.get_model('perf', 'PerformanceAlertSummary')
    for alert in performancealertsummary.objects.all():
        alert.original_prev_push = alert.prev_push
        alert.save()

    performancealertsummarytesting = apps.get_model('perf', 'PerformanceAlertSummaryTesting')
    for alert in performancealertsummarytesting.objects.all():
        alert.original_prev_push = alert.prev_push
        alert.save()

    performancetetemetryalertsummary = apps.get_model('perf', 'PerformanceTelemetryAlertSummary')
    for alert in performancetetemetryalertsummary.objects.all():
        alert.original_prev_push = alert.prev_push
        alert.save()


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0057_performancealert_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealertsummary",
            name="original_prev_push",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="model.push",
            ),
        ),
        migrations.AddField(
            model_name="performancealertsummarytesting",
            name="original_prev_push",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="model.push",
            ),
        ),
        migrations.AddField(
            model_name="performancetelemetryalertsummary",
            name="original_prev_push",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="model.push",
            ),
        ),
    ]
