# Generated by Django 5.1.8 on 2025-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0041_update_search_vector"),
        ("perf", "0058_performancealertsummary_original_prev_push_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performancealert",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="performancealertsummary",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="sheriffed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="performancealertsummary",
            name="sheriffed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="performancealertsummarytesting",
            name="sheriffed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="performancealerttesting",
            name="sheriffed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="performancesignature",
            name="alert_notify_emails",
            field=models.CharField(max_length=422, null=True),
        ),
        migrations.AddField(
            model_name="performancesignature",
            name="monitor",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="performancetelemetryalert",
            name="sheriffed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="performancetelemetryalertsummary",
            name="sheriffed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="performancealert",
            unique_together={("summary", "series_signature", "sheriffed")},
        ),
        migrations.AlterUniqueTogether(
            name="performancealertsummary",
            unique_together={
                ("repository", "framework", "prev_push", "push", "sheriffed")
            },
        ),
    ]
