# Generated by Django 5.1.4 on 2025-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0058_performancealertsummary_original_prev_push_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancebugtemplate",
            name="critical_text",
            field=models.TextField(default="", max_length=4096),
        ),
    ]
