# Generated by Django 5.1.11 on 2025-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0060_alter_performancealert_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetelemetryalert",
            name="bug_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="performancetelemetryalert",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="performancetelemetryalert",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "NEW"),
                    (1, "FIXED"),
                    (2, "INVALID"),
                    (5, "WONTFIX"),
                    (3, "INACTIVE"),
                    (4, "DUPLICATE"),
                    (6, "WORKSFORME"),
                    (7, "INCOMPLETE"),
                    (8, "MOVED"),
                ],
                default=0,
            ),
        ),
    ]
