# Generated by Django 5.1.12 on 2025-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0060_alter_performancealert_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancedatum",
            name="os_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="performancedatum",
            name="platform_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
