# Generated by Django 5.1.12 on 2025-10-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0061_performancetelemetryalert_bug_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetelemetryalert",
            name="bug_modified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="performancetelemetryalertsummary",
            name="bugs_modified",
            field=models.BooleanField(default=True),
        ),
    ]
