# Generated by Django 5.1.12 on 2025-10-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0061_performancedatum_os_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancebugtemplate",
            name="no_action_required_text",
            field=models.TextField(default="", max_length=4096),
        ),
    ]
