# Generated by Django 5.1.14 on 2025-11-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0062_performancetelemetryalert_bug_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancebugtemplate",
            name="no_action_required_text",
            field=models.TextField(default="", max_length=4096),
        ),
    ]
