# Generated by Django 5.1.15 on 2026-03-10 19:13

from django.db import migrations, models

import treeherder.perf.models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0063_performancebugtemplate_no_action_required_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealerttesting",
            name="confidences",
            field=models.JSONField(
                default=treeherder.perf.models.default_detection_methods,
                help_text="A JSON object that indicates the confidence of the alert for each detection method used",
            ),
        ),
    ]
