# Generated by Django 5.1.15 on 2026-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0063_performancebugtemplate_no_action_required_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="backfillrecord",
            name="anchor_push_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backfillrecord",
            name="backfill_logs",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="backfillrecord",
            name="iteration_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="backfillrecord",
            name="last_detected_push_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backfillrecord",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Preliminary"),
                    (1, "Ready for processing"),
                    (2, "Backfilled"),
                    (3, "Successful"),
                    (4, "Failed"),
                    (5, "Verification Failed"),
                ],
                default=0,
            ),
        ),
    ]
