# Generated by Django 5.1.15 on 2026-03-10 20:58

from django.db import migrations, models

import treeherder.perf.models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0064_performancealerttesting_confidences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancealerttesting",
            name="confidences",
            field=models.JSONField(
                default=treeherder.perf.models.default_detection_methods,
                help_text="A JSON object that indicates the confidence of the alert for each detection method used.For methods detecting changes on the culprit revision or in one of the revisions aorund it, the push_idfield indicates the revision where the change was detected.If the change was not detected for a method, the push_id field will correspond to the culprit revisionand the confidecne value will corresoond to the one that of the culprit commit.",
            ),
        ),
    ]
