# Generated by Django 5.1.15 on 2026-03-12 18:04

from django.db import migrations, models

import treeherder.perf.models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0065_alter_performancealerttesting_confidences"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealerttesting",
            name="detected_changes",
            field=models.JSONField(
                default=treeherder.perf.models.default_detection_methods,
                help_text="A JSON object that indicates the confidence of the alert for each detection method used.It has methods detecting changes on the culprit revision or in one of the revisions aorund it, the push_idfield indicates the revision where the change was detected for the given method.",
            ),
        ),
        migrations.AlterField(
            model_name="performancealerttesting",
            name="confidences",
            field=models.JSONField(
                default=dict,
                help_text="A JSON object that contains the confidence values of different methods at the culprit revision.",
            ),
        ),
    ]
