# Generated by Django 5.1.15 on 2026-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "perf",
            "0064_performancealerttesting_confidences_squashed_0068_remove_performancealerttesting_detected_changes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancealerttesting",
            name="new_p90",
        ),
        migrations.RemoveField(
            model_name="performancealerttesting",
            name="prev_p90",
        ),
        migrations.RemoveField(
            model_name="performancetelemetryalert",
            name="new_p90",
        ),
        migrations.RemoveField(
            model_name="performancetelemetryalert",
            name="prev_p90",
        ),
        migrations.AddField(
            model_name="performancealerttesting",
            name="new_p05",
            field=models.FloatField(
                default=0.0, help_text="New P05 value of series after change"
            ),
        ),
        migrations.AddField(
            model_name="performancealerttesting",
            name="prev_p05",
            field=models.FloatField(
                default=0.0, help_text="Previous P05 value of series before change"
            ),
        ),
        migrations.AddField(
            model_name="performancetelemetryalert",
            name="new_p05",
            field=models.FloatField(
                default=0.0, help_text="New P05 value of series after change"
            ),
        ),
        migrations.AddField(
            model_name="performancetelemetryalert",
            name="prev_p05",
            field=models.FloatField(
                default=0.0, help_text="Previous P05 value of series before change"
            ),
        ),
        migrations.AlterField(
            model_name="performancealerttesting",
            name="new_median",
            field=models.FloatField(
                default=0.0, help_text="New median value of series after change"
            ),
        ),
        migrations.AlterField(
            model_name="performancealerttesting",
            name="new_p95",
            field=models.FloatField(
                default=0.0, help_text="New P95 value of series after change"
            ),
        ),
        migrations.AlterField(
            model_name="performancealerttesting",
            name="prev_median",
            field=models.FloatField(
                default=0.0, help_text="Previous median value of series before change"
            ),
        ),
        migrations.AlterField(
            model_name="performancealerttesting",
            name="prev_p95",
            field=models.FloatField(
                default=0.0, help_text="Previous P95 value of series before change"
            ),
        ),
        migrations.AlterField(
            model_name="performancetelemetryalert",
            name="new_median",
            field=models.FloatField(
                default=0.0, help_text="New median value of series after change"
            ),
        ),
        migrations.AlterField(
            model_name="performancetelemetryalert",
            name="new_p95",
            field=models.FloatField(
                default=0.0, help_text="New P95 value of series after change"
            ),
        ),
        migrations.AlterField(
            model_name="performancetelemetryalert",
            name="prev_median",
            field=models.FloatField(
                default=0.0, help_text="Previous median value of series before change"
            ),
        ),
        migrations.AlterField(
            model_name="performancetelemetryalert",
            name="prev_p95",
            field=models.FloatField(
                default=0.0, help_text="Previous P95 value of series before change"
            ),
        ),
    ]
