# Generated by Django 5.1.15 on 2026-04-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0069_remove_performancealerttesting_new_p90_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performancealerttesting",
            unique_together={
                ("summary", "detection_method"),
                ("summary", "series_signature"),
                ("summary", "telemetry_series_signature"),
            },
        ),
    ]
