# Generated by Django 5.1.15 on 2026-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0069_remove_performancealerttesting_new_p90_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetelemetrysignature",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-10-10 00:00:00+00:00"
            ),
            preserve_default=False,
        ),
    ]
