# Generated by Django 5.1.15 on 2026-04-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0070_performancetelemetrysignature_created"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performancealerttesting",
            unique_together={
                (
                    "summary",
                    "series_signature",
                    "telemetry_series_signature",
                    "detection_method",
                )
            },
        ),
    ]
