# Generated by Django 5.1.15 on 2026-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0071_alter_performancealerttesting_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetelemetryalert",
            name="additional_data",
            field=models.JSONField(
                default=dict,
                help_text="This field can be used to store additional data in JSON format that doesn't fit in any of the other fields. Custom CDP techniques can use this field to store extra non-standard data.",
            ),
        ),
    ]
