# Generated by Django 5.2.12 on 2026-04-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0072_performancetelemetryalert_additional_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancesignature",
            name="alert_severity",
            field=models.CharField(
                choices=[
                    ("critical", "critical"),
                    ("subcritical", "subcritical"),
                    ("normal", "normal"),
                ],
                default="normal",
                max_length=80,
            ),
        ),
    ]
