# Generated by Django 5.2.12 on 2026-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0074_remove_raptor_framework"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealertsummary",
            name="bug_status",
            field=models.IntegerField(
                choices=[
                    (0, "NEW"),
                    (1, "FIXED"),
                    (2, "INVALID"),
                    (3, "INACTIVE"),
                    (4, "DUPLICATE"),
                    (5, "WONTFIX"),
                    (6, "WORKSFORME"),
                    (7, "INCOMPLETE"),
                    (8, "MOVED"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
