# Generated by Django 6.0.3 on 2026-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0077_add_infra_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfCompareMwuCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("results", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "perf_compare_mwu_cache",
            },
        ),
    ]
