# Generated by Django 6.0.3 on 2026-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0077_add_infra_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancetelemetryalert",
            name="is_regression",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="performancetelemetrysignature",
            name="lower_is_better",
            field=models.BooleanField(null=True),
        ),
    ]
