# Generated by Django 6.0.3 on 2026-07-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0078_alter_performancetelemetryalert_is_regression_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performancetelemetrysignature",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="performancetelemetrysignature",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label of the probe for labeled probe types (e.g. labeled_timing_distribution). Each label of those probes holds its own timeseries so it needs its own signature. Empty for unlabeled probes.",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancetelemetrysignature",
            unique_together={
                ("channel", "probe", "probe_type", "platform", "application", "label")
            },
        ),
    ]
