# Generated by Django 6.0.3 on 2026-08-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0053_push_branch"),
        ("perf", "0079_alter_performancetelemetrysignature_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackfillRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bk_task_id", models.CharField(db_index=True, max_length=255)),
                (
                    "strategy",
                    models.IntegerField(
                        blank=True, choices=[(0, "Standard"), (1, "Sliced")], null=True
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("slices", models.IntegerField(blank=True, null=True)),
                ("target_hg_push_ids", models.JSONField(default=list)),
                ("scanned_push_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Synced"), (2, "Failed")],
                        default=0,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backfill_requests",
                        to="model.job",
                    ),
                ),
                (
                    "push",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model.repository",
                    ),
                ),
            ],
            options={
                "db_table": "backfill_request",
            },
        ),
        migrations.CreateModel(
            name="BackfilledPush",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision_task_id", models.CharField(max_length=255)),
                (
                    "action_task_id",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Created"),
                            (2, "Skipped"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backfilled_pushes",
                        to="model.job",
                    ),
                ),
                (
                    "push",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="model.push",
                    ),
                ),
                (
                    "backfill_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backfilled_pushes",
                        to="perf.backfillrequest",
                    ),
                ),
            ],
            options={
                "db_table": "backfilled_push",
                "unique_together": {("backfill_request", "push")},
            },
        ),
    ]
