# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:50
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        (b'credentials', '0001_initial'),
        (b'credentials', '0002_auto_20151014_0900'),
        (b'credentials', '0003_allow_credentials_with_no_owner'),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SlugField(max_length=32, unique=True, verbose_name=b'client ID')),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField()),
                ('authorized', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials',
                'verbose_name_plural': 'credentials',
            },
        ),
    ]
