from treeherder.etl import buildbot
import pytest

slow = pytest.mark.slow

buildernames = [
 ('Android 2.2 Armv6 mozilla-inbound build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'Android 2.2 Armv6 mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'armv6',
                'os': 'android',
                'os_platform': 'android-2-2-armv6',
                'vm': False}}),
 ('Android 2.2 Armv6 Tegra mozilla-inbound opt test crashtest',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Android 2.2 Armv6 Tegra mozilla-inbound opt test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'armv6',
                'os': 'android',
                'os_platform': 'android-2-2-armv6',
                'vm': False}}),
 ('Android 2.2 Armv6 Tegra mozilla-inbound opt test jsreftest-1',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Android 2.2 Armv6 Tegra mozilla-inbound opt test jsreftest-1',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'JSReftest',
            'symbol': 'J1'},
   'platform': {'arch': 'armv6',
                'os': 'android',
                'os_platform': 'android-2-2-armv6',
                'vm': False}}),
 ('Android 2.2 Armv6 Tegra mozilla-inbound opt test mochitest-1',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Android 2.2 Armv6 Tegra mozilla-inbound opt test mochitest-1',
            'group_name': 'Mochitest',
            'group_symbol': 'M',
            'name': 'Mochitest',
            'symbol': '1'},
   'platform': {'arch': 'armv6',
                'os': 'android',
                'os_platform': 'android-2-2-armv6',
                'vm': False}}),
 ('Android 2.2 Armv6 Tegra mozilla-inbound opt test plain-reftest-1',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Android 2.2 Armv6 Tegra mozilla-inbound opt test plain-reftest-1',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Reftest',
            'symbol': 'R1'},
   'platform': {'arch': 'armv6',
                'os': 'android',
                'os_platform': 'android-2-2-armv6',
                'vm': False}}),
 ('Android 2.2 Armv6 Tegra mozilla-inbound opt test robocop-1',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Android 2.2 Armv6 Tegra mozilla-inbound opt test robocop-1',
            'group_name': 'Mochitest',
            'group_symbol': 'M',
            'name': 'Robocop',
            'symbol': 'rc1'},
   'platform': {'arch': 'armv6',
                'os': 'android',
                'os_platform': 'android-2-2-armv6',
                'vm': False}}),
 ('Android 2.2 Armv6 Tegra mozilla-inbound opt test xpcshell',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Android 2.2 Armv6 Tegra mozilla-inbound opt test xpcshell',
            'group_name': None,
            'group_symbol': '?',
            'name': 'XPCShellTest',
            'symbol': 'X'},
   'platform': {'arch': 'armv6',
                'os': 'android',
                'os_platform': 'android-2-2-armv6',
                'vm': False}}),
 ('Android 2.2 Debug mozilla-inbound build',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'Android 2.2 Debug mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'android',
                'os_platform': 'android-2-2',
                'vm': False}}),
 ('Android 2.2 mozilla-inbound build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'Android 2.2 mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'android',
                'os_platform': 'android-2-2',
                'vm': False}}),
 ('Android 2.2 Tegra mozilla-inbound opt test crashtest',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Android 2.2 Tegra mozilla-inbound opt test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86',
                'os': 'android',
                'os_platform': 'android-2-2',
                'vm': False}}),
 ('Android 2.2 Tegra mozilla-inbound talos remote-tcanvasmark',
  {'build_type': 'opt',
   'job_type': 'talos',
   'name': {'buildername': 'Android 2.2 Tegra mozilla-inbound talos remote-tcanvasmark',
            'group_name': 'Talos Performance',
            'group_symbol': 'T',
            'name': 'Talos canvasmark',
            'symbol': 'cm'},
   'platform': {'arch': 'x86',
                'os': 'android',
                'os_platform': 'android-2-2',
                'vm': False}}),
 ('Android 4.0 Panda mozilla-inbound talos remote-tsvgx',
  {'build_type': 'opt',
   'job_type': 'talos',
   'name': {'buildername': 'Android 4.0 Panda mozilla-inbound talos remote-tsvgx',
            'group_name': 'Talos Performance',
            'group_symbol': 'T',
            'name': 'Talos svg',
            'symbol': 's'},
   'platform': {'arch': 'x86',
                'os': 'android',
                'os_platform': 'android-4-0',
                'vm': False}}),
 ('Android 4.2 x86 mozilla-inbound build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'Android 4.2 x86 mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'android',
                'os_platform': 'android-4-2-x86',
                'vm': False}}),
 ('b2g_emulator mozilla-inbound opt test reftest-1',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'b2g_emulator mozilla-inbound opt test reftest-1',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Reftest',
            'symbol': 'R1'},
   'platform': {'arch': 'x86',
                'os': 'b2g',
                'os_platform': 'b2g-emu-ics',
                'vm': False}}),
 ('b2g_mozilla-inbound_emulator_dep',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_emulator_dep',
            'group_name': None,
            'group_symbol': '?',
            'name': 'B2G Emulator Image Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'b2g',
                'os_platform': 'b2g-emu-ics',
                'vm': False}}),
 ('b2g_mozilla-inbound_emulator-debug_dep',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_emulator-debug_dep',
            'group_name': None,
            'group_symbol': '?',
            'name': 'B2G Emulator Image Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'b2g',
                'os_platform': 'b2g-emu-ics',
                'vm': False}}),
 ('b2g_mozilla-inbound_emulator-jb_dep',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_emulator-jb_dep',
            'group_name': None,
            'group_symbol': '?',
            'name': 'B2G Emulator Image Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'b2g',
                'os_platform': 'b2g-emu-jb',
                'vm': False}}),
 ('b2g_mozilla-inbound_emulator-jb-debug_dep',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_emulator-jb-debug_dep',
            'group_name': None,
            'group_symbol': '?',
            'name': 'B2G Emulator Image Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'b2g',
                'os_platform': 'b2g-emu-jb',
                'vm': False}}),
 ('b2g_mozilla-inbound_linux32_gecko build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_linux32_gecko build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'b2g-linux32',
                'vm': False}}),
 ('b2g_mozilla-inbound_linux64_gecko build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_linux64_gecko build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'b2g-linux64',
                'vm': False}}),
 ('b2g_mozilla-inbound_macosx64_gecko build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_macosx64_gecko build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'b2g-osx',
                'vm': False}}),
 ('b2g_mozilla-inbound_unagi_dep',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_unagi_dep',
            'group_name': 'Unagi Device Image',
            'group_symbol': 'Unagi',
            'name': 'Unagi Device Image Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'b2g',
                'os_platform': 'b2g-device-image',
                'vm': False}}),
 ('b2g_mozilla-inbound_win32_gecko build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'b2g_mozilla-inbound_win32_gecko build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'win',
                'os_platform': 'b2g-win32',
                'vm': False}}),
 ('b2g_ubuntu64_vm mozilla-inbound opt test gaia-ui-test',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'b2g_ubuntu64_vm mozilla-inbound opt test gaia-ui-test',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Gaia UI Test',
            'symbol': 'Gu'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'b2g-linux64',
                'vm': True}}),
 ('b2g_ubuntu64_vm mozilla-inbound opt test gaia-unit',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'b2g_ubuntu64_vm mozilla-inbound opt test gaia-unit',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Gaia Unit Test',
            'symbol': 'G'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'b2g-linux64',
                'vm': True}}),
 ('b2g_ubuntu64_vm mozilla-inbound opt test mochitest-1',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'b2g_ubuntu64_vm mozilla-inbound opt test mochitest-1',
            'group_name': 'Mochitest',
            'group_symbol': 'M',
            'name': 'Mochitest',
            'symbol': '1'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'b2g-linux64',
                'vm': True}}),
 ('Linux mozilla-inbound build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'Linux mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': False}}),
 ('Linux mozilla-inbound leak test build',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'Linux mozilla-inbound leak test build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': False}}),
 ('Linux mozilla-inbound leak test spidermonkey_info-warnaserrdebug build',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'Linux mozilla-inbound leak test spidermonkey_info-warnaserrdebug build',
            'group_name': 'SpiderMonkey',
            'group_symbol': 'SM',
            'name': 'SpiderMonkey --enable-sm-fail-on-warnings Build',
            'symbol': 'e'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': False}}),
 ('Linux mozilla-inbound pgo-build',
  {'build_type': 'pgo',
   'job_type': 'build',
   'name': {'buildername': 'Linux mozilla-inbound pgo-build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': False}}),
 ('Linux mozilla-inbound spidermonkey_info-warnaserr build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'Linux mozilla-inbound spidermonkey_info-warnaserr build',
            'group_name': 'SpiderMonkey',
            'group_symbol': 'SM',
            'name': 'SpiderMonkey --enable-sm-fail-on-warnings Build',
            'symbol': 'e'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound asan build',
  {'build_type': 'asan',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound asan build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'AddressSanitizer Opt Build',
            'symbol': 'Bo'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound debug asan build',
  {'build_type': 'asan',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound debug asan build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'AddressSanitizer Debug Build',
            'symbol': 'Bd'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound debug static analysis build',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound debug static analysis build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Static Checking Build',
            'symbol': 'S'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound leak test build',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound leak test build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound leak test spidermonkey_tier_1-rootanalysis build',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound leak test spidermonkey_tier_1-rootanalysis build',
            'group_name': 'SpiderMonkey',
            'group_symbol': 'SM',
            'name': 'SpiderMonkey --enable-root-analysis Build',
            'symbol': 'r'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound pgo-build',
  {'build_type': 'pgo',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound pgo-build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Linux x86-64 mozilla-inbound spidermonkey_info-warnaserr build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'Linux x86-64 mozilla-inbound spidermonkey_info-warnaserr build',
            'group_name': 'SpiderMonkey',
            'group_symbol': 'SM',
            'name': 'SpiderMonkey --enable-sm-fail-on-warnings Build',
            'symbol': 'e'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('OS X 10.7 64-bit mozilla-inbound leak test build',
  {'build_type': 'debug',
   'job_type': 'build',
   'name': {'buildername': 'OS X 10.7 64-bit mozilla-inbound leak test build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-7',
                'vm': False}}),
 ('OS X 10.7 mozilla-inbound build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'OS X 10.7 mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-7',
                'vm': False}}),
 ('Rev3 Fedora 12 mozilla-inbound debug test mochitest-browser-chrome',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Rev3 Fedora 12 mozilla-inbound debug test mochitest-browser-chrome',
            'group_name': 'Mochitest',
            'group_symbol': 'M',
            'name': 'Mochitest Browser Chrome',
            'symbol': 'bc'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': False}}),
 ('Rev3 Fedora 12x64 mozilla-inbound debug test mochitest-browser-chrome',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Rev3 Fedora 12x64 mozilla-inbound debug test mochitest-browser-chrome',
            'group_name': 'Mochitest',
            'group_symbol': 'M',
            'name': 'Mochitest Browser Chrome',
            'symbol': 'bc'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Rev4 MacOSX Lion 10.7 mozilla-inbound debug test jetpack',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Rev4 MacOSX Lion 10.7 mozilla-inbound debug test jetpack',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Jetpack SDK Test',
            'symbol': 'JP'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-7',
                'vm': False}}),
 ('Rev4 MacOSX Lion 10.7 mozilla-inbound debug test marionette',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Rev4 MacOSX Lion 10.7 mozilla-inbound debug test marionette',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Marionette Framework Unit Tests',
            'symbol': 'Mn'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-7',
                'vm': False}}),
 ('Rev4 MacOSX Lion 10.7 mozilla-inbound debug test reftest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Rev4 MacOSX Lion 10.7 mozilla-inbound debug test reftest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Reftest',
            'symbol': 'R'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-7',
                'vm': False}}),
 ('Rev4 MacOSX Lion 10.7 mozilla-inbound talos dromaeojs',
  {'build_type': 'opt',
   'job_type': 'talos',
   'name': {'buildername': 'Rev4 MacOSX Lion 10.7 mozilla-inbound talos dromaeojs',
            'group_name': 'Talos Performance',
            'group_symbol': 'T',
            'name': 'Talos dromaeojs',
            'symbol': 'd'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-7',
                'vm': False}}),
 ('Rev4 MacOSX Snow Leopard 10.6 mozilla-inbound debug test crashtest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Rev4 MacOSX Snow Leopard 10.6 mozilla-inbound debug test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-6',
                'vm': False}}),
 ('Rev5 MacOSX Mountain Lion 10.8 mozilla-inbound debug test crashtest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Rev5 MacOSX Mountain Lion 10.8 mozilla-inbound debug test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86_64',
                'os': 'mac',
                'os_platform': 'osx-10-8',
                'vm': False}}),
 ('Ubuntu ASAN VM 12.04 x64 mozilla-inbound opt test crashtest',
  {'build_type': 'opt',
   'job_type': 'unittest',
   'name': {'buildername': 'Ubuntu ASAN VM 12.04 x64 mozilla-inbound opt test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': True}}),
 ('Ubuntu VM 12.04 x64 mozilla-inbound debug test marionette',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Ubuntu VM 12.04 x64 mozilla-inbound debug test marionette',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Marionette Framework Unit Tests',
            'symbol': 'Mn'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': True}}),
 ('Ubuntu HW 12.04 mozilla-inbound pgo talos chromez',
  {'build_type': 'pgo',
   'job_type': 'talos',
   'name': {'buildername': 'Ubuntu HW 12.04 mozilla-inbound pgo talos chromez',
            'group_name': 'Talos Performance',
            'group_symbol': 'T',
            'name': 'Talos chrome',
            'symbol': 'c'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': False}}),
 ('Ubuntu HW 12.04 x64 mozilla-inbound pgo talos chromez',
  {'build_type': 'pgo',
   'job_type': 'talos',
   'name': {'buildername': 'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos chromez',
            'group_name': 'Talos Performance',
            'group_symbol': 'T',
            'name': 'Talos chrome',
            'symbol': 'c'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': False}}),
 ('Ubuntu VM 12.04 mozilla-inbound debug test crashtest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Ubuntu VM 12.04 mozilla-inbound debug test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86',
                'os': 'linux',
                'os_platform': 'linux32',
                'vm': True}}),
 ('Ubuntu VM 12.04 x64 mozilla-inbound debug test crashtest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Ubuntu VM 12.04 x64 mozilla-inbound debug test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86_64',
                'os': 'linux',
                'os_platform': 'linux64',
                'vm': True}}),
 ('Windows 7 32-bit mozilla-inbound debug test crashtest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Windows 7 32-bit mozilla-inbound debug test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86',
                'os': 'win',
                'os_platform': 'windows7-32',
                'vm': False}}),
 ('Windows XP 32-bit mozilla-inbound debug test crashtest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'Windows XP 32-bit mozilla-inbound debug test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86',
                'os': 'win',
                'os_platform': 'windowsxp',
                'vm': False}}),
 ('WINNT 5.2 mozilla-inbound build',
  {'build_type': 'opt',
   'job_type': 'build',
   'name': {'buildername': 'WINNT 5.2 mozilla-inbound build',
            'group_name': None,
            'group_symbol': '?',
            'name': 'Build',
            'symbol': 'B'},
   'platform': {'arch': 'x86',
                'os': 'win',
                'os_platform': 'windowsxp',
                'vm': False}}),
 ('WINNT 6.2 mozilla-inbound debug test crashtest',
  {'build_type': 'debug',
   'job_type': 'unittest',
   'name': {'buildername': 'WINNT 6.2 mozilla-inbound debug test crashtest',
            'group_name': 'Reftest',
            'group_symbol': 'R',
            'name': 'Crashtest',
            'symbol': 'C'},
   'platform': {'arch': 'x86',
                'os': 'win',
                'os_platform': 'windows8-32',
                'vm': False}})
]


@pytest.mark.parametrize(('buildername', 'exp_result'), buildernames)
def test_buildername_translation(buildername, exp_result):
    """
    test getting the right platform based on the buildername
    """

    assert buildbot.extract_platform_info(buildername) == exp_result["platform"]
    assert buildbot.extract_job_type(buildername) == exp_result["job_type"]
    assert buildbot.extract_build_type(buildername) == exp_result["build_type"]
