import pytest

from treeherder.etl import buildbot

slow = pytest.mark.slow

buildernames = [
    ('Android 2.2 Armv6 mozilla-inbound build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv6',
                   'os': 'android',
                   'os_platform': 'android-2-2-armv6'}}),
    ('Android 2.2 Armv6 Tegra mozilla-inbound opt test crashtest',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'armv6',
                   'os': 'android',
                   'os_platform': 'android-2-2-armv6'}}),
    ('Android 2.2 Armv6 Tegra mozilla-inbound opt test jsreftest-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'JSReftest',
               'job_symbol': 'J1'},
      'platform': {'arch': 'armv6',
                   'os': 'android',
                   'os_platform': 'android-2-2-armv6'}}),
    ('Android 2.2 Armv6 Tegra mozilla-inbound opt test mochitest-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest',
               'job_symbol': '1'},
      'platform': {'arch': 'armv6',
                   'os': 'android',
                   'os_platform': 'android-2-2-armv6'}}),
    ('Ubuntu VM 12.04 x64 mozilla-central opt test mochitest-e10s-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest e10s',
               'group_symbol': 'M-e10s',
               'name': 'Mochitest e10s',
               'job_symbol': '1'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('b2g_ubuntu64_vm mozilla-central opt test mochitest-oop-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest OOP',
               'group_symbol': 'M-oop',
               'name': 'Mochitest OOP',
               'job_symbol': '1'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_emulator mozilla-central opt test mochitest-chrome',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest Chrome',
               'job_symbol': 'c'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-emu-ics'}}),
    ('Windows XP 32-bit mozilla-central opt test mochitest-chrome-2',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest Chrome',
               'job_symbol': 'c2'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windowsxp'}}),
    ('Windows XP 32-bit mozilla-central pgo test mochitest-a11y',
     {'build_type': 'pgo',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest a11y',
               'job_symbol': 'a'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windowsxp'}}),
    ('Ubuntu VM 12.04 mozilla-central opt test jittest-2',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'JIT Tests',
               'job_symbol': 'Jit2'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Rev4 MacOSX Snow Leopard 10.6 mozilla-central debug test mochitest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest',
               'job_symbol': 'M'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-6'}}),
    ('Rev4 MacOSX Snow Leopard 10.6 mozilla-central debug test mochitest-devtools-chrome-2',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest DevTools Browser Chrome',
               'job_symbol': 'dt2'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-6'}}),
    ('Android 2.2 Tegra mozilla-inbound opt test mochitest-6',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest',
               'job_symbol': '6'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-2'}}),
    ('Android 2.2 Armv6 Tegra mozilla-inbound opt test plain-reftest-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Reftest',
               'job_symbol': 'R1'},
      'platform': {'arch': 'armv6',
                   'os': 'android',
                   'os_platform': 'android-2-2-armv6'}}),
    ('Android 2.2 Armv6 Tegra mozilla-inbound opt test robocop-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Robocop',
               'job_symbol': 'rc1'},
      'platform': {'arch': 'armv6',
                   'os': 'android',
                   'os_platform': 'android-2-2-armv6'}}),
    ('Android 2.2 Armv6 Tegra mozilla-inbound opt test xpcshell',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'XPCShell',
               'job_symbol': 'X'},
      'platform': {'arch': 'armv6',
                   'os': 'android',
                   'os_platform': 'android-2-2-armv6'}}),
    ('Android 2.2 Debug mozilla-inbound build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-2'}}),
    ('Android 2.2 mozilla-inbound build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-2'}}),
    ('Android 2.2 Tegra mozilla-inbound opt test crashtest',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-2'}}),
    ('Android 4.0 Panda mozilla-inbound talos remote-tsvgx',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos svg',
               'job_symbol': 's'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0'}}),
    ('Android 4.2 x86 mozilla-inbound build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'android',
                   'os_platform': 'android-4-2-x86'}}),
    ('b2g_emulator mozilla-inbound opt test reftest-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Reftest',
               'job_symbol': 'R1'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-emu-ics'}}),
    ('b2g_mozilla-inbound_emulator_dep',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'B2G Emulator Image Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-emu-ics'}}),
    ('b2g_mozilla-inbound_emulator-debug_dep',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'B2G Emulator Image Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-emu-ics'}}),
    ('b2g_mozilla-inbound_emulator-jb_dep',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'B2G Emulator Image Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-emu-jb'}}),
    ('b2g_mozilla-inbound_emulator-jb-debug_dep',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'B2G Emulator Image Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-emu-jb'}}),
    ('b2g_mozilla-inbound_linux32_gecko build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'b2g-linux32'}}),
    ('b2g_mozilla-inbound_linux64_gecko build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_mozilla-inbound_macosx64_gecko build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'b2g-osx'}}),
    ('b2g_mozilla-inbound_unagi_dep',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Unagi Device Image',
               'group_symbol': 'Unagi',
               'name': 'Unagi Device Image Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('b2g_mozilla-inbound_win32_gecko build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'b2g-win32'}}),
    ('b2g_ubuntu64_vm mozilla-inbound opt test gaia-integration',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia JS Integration Test',
               'group_symbol': 'Gij',
               'name': 'Gaia JS Integration Test',
               'job_symbol': 'Gij'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm cedar debug test gaia-js-integration-4',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia JS Integration Test',
               'group_symbol': 'Gij',
               'name': 'Gaia JS Integration Test',
               'job_symbol': '4'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm cedar debug test gaia-js-integration-oop-1',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia JS Integration Test OOP',
               'group_symbol': 'Gij-oop',
               'name': 'Gaia JS Integration Test OOP',
               'job_symbol': '1'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm mozilla-inbound opt test gaia-ui-test',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests',
               'group_symbol': 'Gip',
               'name': 'Gaia Python Integration Tests',
               'job_symbol': 'Gip'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_macosx64 cedar opt test gaia-ui-test-accessibility',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests',
               'group_symbol': 'Gip',
               'name': 'Gaia Python Accessibility Integration Tests',
               'job_symbol': 'a'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'b2g-osx'}}),
    ('b2g_ubuntu64_vm cedar opt test gaia-ui-test-functional-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests',
               'group_symbol': 'Gip',
               'name': 'Gaia Python Functional Integration Tests',
               'job_symbol': 'f1'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm cedar opt test gaia-ui-test-unit',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests',
               'group_symbol': 'Gip',
               'name': 'Gaia Python Integration Unit Tests',
               'job_symbol': 'u'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm cedar opt test gaia-ui-test-oop',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests OOP',
               'group_symbol': 'Gip-oop',
               'name': 'Gaia Python Integration Tests OOP',
               'job_symbol': 'Gip-oop'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_macosx64 cedar opt test gaia-ui-test-oop-accessibility',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests OOP',
               'group_symbol': 'Gip-oop',
               'name': 'Gaia Python Accessibility Integration Tests OOP',
               'job_symbol': 'a'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'b2g-osx'}}),
    ('b2g_ubuntu64_vm cedar opt test gaia-ui-test-oop-functional-3',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests OOP',
               'group_symbol': 'Gip-oop',
               'name': 'Gaia Python Functional Integration Tests OOP',
               'job_symbol': 'f3'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm cedar opt test gaia-ui-test-oop-unit',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Gaia Python Integration Tests OOP',
               'group_symbol': 'Gip-oop',
               'name': 'Gaia Python Integration Unit Tests OOP',
               'job_symbol': 'u'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm mozilla-inbound opt test gaia-unit',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Gaia Unit Test',
               'job_symbol': 'Gu'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm cedar opt test gaia-unit-oop',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Gaia Unit Test OOP',
               'job_symbol': 'Gu-oop'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm gaia-try opt test gaia-build',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Gaia Build Test',
               'job_symbol': 'Gb'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm gaia-try opt test gaia-build-unit',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Gaia Build Unit Test',
               'job_symbol': 'Gbu'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('b2g_ubuntu64_vm mozilla-inbound opt test mochitest-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest',
               'job_symbol': '1'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'b2g-linux64'}}),
    ('Linux x86-64 Mulet cedar build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'mulet-linux64'}}),
    ('Ubuntu VM 12.04 x64 Mulet cedar opt test mochitest-5',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest',
               'job_symbol': '5'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'mulet-linux64'}}),
    ('OS X Mulet cedar non-unified',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Non-Unified Build',
               'job_symbol': 'Bn'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'mulet-osx'}}),
    ('Win32 Mulet cedar build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'mulet-win32'}}),
    ('graphene_cedar_linux64 build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'graphene-linux64'}}),
    ('horizon_cedar_linux64 build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'horizon-linux64'}}),
    ('Linux x86_64 Code Coverage cedar build',
     {'build_type': 'cc',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu Code Coverage VM 12.04 x64 cedar opt test web-platform-tests-2',
     {'build_type': 'cc',
      'job_type': 'unittest',
      'name': {'group_name': 'W3C Web Platform Tests',
               'group_symbol': 'W',
               'name': 'W3C Web Platform Tests',
               'job_symbol': '2'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux mozilla-inbound build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Linux mozilla-inbound leak test build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Linux mozilla-inbound leak test spidermonkey_info-warnaserrdebug build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'SpiderMonkey',
               'group_symbol': 'SM',
               'name': 'SpiderMonkey Fail-On-Warnings Build',
               'job_symbol': 'e'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Linux mozilla-inbound pgo-build',
     {'build_type': 'pgo',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Linux mozilla-inbound spidermonkey_info-warnaserr build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'SpiderMonkey',
               'group_symbol': 'SM',
               'name': 'SpiderMonkey Fail-On-Warnings Build',
               'job_symbol': 'e'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Linux x86-64 mozilla-inbound asan build',
     {'build_type': 'asan',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'AddressSanitizer Opt Build',
               'job_symbol': 'Bo'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 try tsan build',
     {'build_type': 'tsan',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound debug asan build',
     {'build_type': 'asan',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'AddressSanitizer Debug Build',
               'job_symbol': 'Bd'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-beta add-on-devel build',
     {'build_type': 'addon',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound debug static analysis build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Static Checking Build',
               'job_symbol': 'S'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound leak test build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound leak test non-unified',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Non-Unified Build',
               'job_symbol': 'Bn'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound non-unified',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Non-Unified Build',
               'job_symbol': 'Bn'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound leak test spidermonkey_tier_1-rootanalysis '
     'build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'SpiderMonkey',
               'group_symbol': 'SM',
               'name': 'SpiderMonkey Root Analysis Build',
               'job_symbol': 'r'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound pgo-build',
     {'build_type': 'pgo',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound spidermonkey_info-warnaserr build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'SpiderMonkey',
               'group_symbol': 'SM',
               'name': 'SpiderMonkey Fail-On-Warnings Build',
               'job_symbol': 'e'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Linux x86-64 mozilla-inbound leak test spidermonkey_tier_1-arm64-sim build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'SpiderMonkey',
               'group_symbol': 'SM',
               'name': 'SpiderMonkey ARM64 Simulator Build',
               'job_symbol': 'arm64'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('OS X 10.7 64-bit mozilla-inbound leak test build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-7'}}),
    ('OS X 10.7 mozilla-inbound build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-7'}}),
    ('Rev4 MacOSX Lion 10.7 mozilla-inbound debug test jetpack',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Jetpack SDK Test',
               'job_symbol': 'JP'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-7'}}),
    ('Rev4 MacOSX Lion 10.7 mozilla-inbound debug test marionette',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Marionette Framework Unit Tests',
               'job_symbol': 'Mn'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-7'}}),
    ('Rev7 MacOSX Yosemite 10.10.5 try opt test mochitest-browser-screenshots',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest Browser Screenshots',
               'job_symbol': 'ss'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Ubuntu VM 12.04 cedar opt test marionette-e10s',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Marionette Framework Unit Tests e10s',
               'job_symbol': 'Mn-e10s'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Rev5 MacOSX Yosemite 10.10 try opt test gtest',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'GTest Unit Tests',
               'job_symbol': 'GTest'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev4 MacOSX Lion 10.7 mozilla-inbound debug test reftest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Reftest',
               'job_symbol': 'R'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-7'}}),
    ('Rev4 MacOSX Lion 10.7 mozilla-inbound talos dromaeojs',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos dromaeojs',
               'job_symbol': 'd'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-7'}}),
    ('Rev4 MacOSX Snow Leopard 10.6 mozilla-inbound debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-6'}}),
    ('Rev5 MacOSX Mountain Lion 10.8 mozilla-inbound debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-8'}}),
    ('Ubuntu ASAN VM 12.04 x64 mozilla-inbound opt test crashtest',
     {'build_type': 'asan',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu ASAN VM 12.04 x64 cedar opt test reftest-no-accel-e10s',
     {'build_type': 'asan',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest e10s',
               'group_symbol': 'R-e10s',
               'name': 'Reftest Unaccelerated e10s',
               'job_symbol': 'Ru'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu VM 12.04 x64 mozilla-inbound debug test marionette',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Marionette Framework Unit Tests',
               'job_symbol': 'Mn'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu HW 12.04 mozilla-central pgo talos other_nol64',
     {'build_type': 'pgo',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos other',
               'job_symbol': 'o'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Ubuntu HW 12.04 mozilla-central pgo talos g1',
     {'build_type': 'pgo',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos g1',
               'job_symbol': 'g1'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Ubuntu HW 12.04 mozilla-central pgo talos g2',
     {'build_type': 'pgo',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos g2',
               'job_symbol': 'g2'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Ubuntu HW 12.04 mozilla-inbound pgo talos chromez',
     {'build_type': 'pgo',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos chrome',
               'job_symbol': 'c'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Ubuntu HW 12.04 x64 mozilla-inbound pgo talos chromez',
     {'build_type': 'pgo',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos chrome',
               'job_symbol': 'c'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu VM 12.04 mozilla-inbound debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Ubuntu VM 12.04 x64 mozilla-inbound debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Windows 7 32-bit mozilla-inbound debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows7-32'}}),
    ('Windows 7 32-bit mozilla-inbound debug test mochitest-gl-e10s',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest e10s',
               'group_symbol': 'M-e10s',
               'name': 'Mochitest e10s WebGL',
               'job_symbol': 'gl'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows7-32'}}),
    ('Windows 7 32-bit mozilla-inbound debug test mochitest-push-e10s',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest e10s',
               'group_symbol': 'M-e10s',
               'name': 'Mochitest e10s Push',
               'job_symbol': 'p'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows7-32'}}),
    ('Windows 7 32-bit mozilla-inbound debug test mochitest-media',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest Media',
               'job_symbol': 'mda'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows7-32'}}),
    ('Windows 7 VM-GFX 32-bit try debug test mochitest-media',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest Media',
               'job_symbol': 'mda'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows7-32'}}),
    ('Windows XP 32-bit mozilla-inbound debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windowsxp'}}),
    ('WINNT 5.2 mozilla-inbound build',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windowsxp'}}),
    ('WINNT 6.2 mozilla-inbound debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows8-32'}}),
    ('WINNT 6.1 x86-64 date leak test build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'x86_64',
                   'os': 'win',
                   'os_platform': 'windows8-64'}}),
    ('Windows 8 64-bit date opt test mochitest-e10s-browser-chrome-3',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest e10s',
               'group_symbol': 'M-e10s',
               'name': 'Mochitest e10s Browser Chrome',
               'job_symbol': 'bc3'},
      'platform': {'arch': 'x86_64',
                   'os': 'win',
                   'os_platform': 'windows8-64'}}),
    ('Windows 10 32-bit larch opt test mochitest-browser-chrome-3',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest Browser Chrome',
               'job_symbol': 'bc3'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows10-32'}}),
    ('Windows 10 64-bit date debug test mochitest-e10s-browser-chrome-3',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest e10s',
               'group_symbol': 'M-e10s',
               'name': 'Mochitest e10s Browser Chrome',
               'job_symbol': 'bc3'},
      'platform': {'arch': 'x86_64',
                   'os': 'win',
                   'os_platform': 'windows10-64'}}),
    ('Linux x86-64 b2g-inbound valgrind',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Valgrind Build',
               'job_symbol': 'V'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('b2g_mozilla-b2g18_leo_eng_nightly',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Leo Device Image',
               'group_symbol': 'Leo',
               'name': 'Leo Device Image Nightly (Engineering)',
               'job_symbol': 'Ne'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('b2g_mozilla-b2g26_v1_2_hamachi_nightly',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Buri/Hamachi Device Image',
               'group_symbol': 'Buri/Hamachi',
               'name': 'Hamachi Device Image Nightly',
               'job_symbol': 'N'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('b2g_mozilla-b2g34_v2_1s_dolphin_nightly',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Dolphin Device Image',
               'group_symbol': 'Dolphin',
               'name': 'Dolphin Device Image Nightly',
               'job_symbol': 'N'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('b2g_mozilla-b2g34_v2_1s_dolphin_eng_nightly',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Dolphin Device Image',
               'group_symbol': 'Dolphin',
               'name': 'Dolphin Device Image Nightly (Engineering)',
               'job_symbol': 'Ne'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('b2g_mozilla-b2g34_v2_1s_dolphin-512_nightly',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Dolphin-512 Device Image',
               'group_symbol': 'Dolphin-512',
               'name': 'Dolphin-512 Device Image Nightly',
               'job_symbol': 'N'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('b2g_mozilla-b2g34_v2_1s_dolphin-512_eng_nightly',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Dolphin-512 Device Image',
               'group_symbol': 'Dolphin-512',
               'name': 'Dolphin-512 Device Image Nightly (Engineering)',
               'job_symbol': 'Ne'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('jetpack-fx-team-snowleopard-debug',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Jetpack SDK Test',
               'job_symbol': 'JP'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-6'}}),
    ('jetpack-fx-team-snowleopard-opt',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Jetpack SDK Test',
               'job_symbol': 'JP'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-6'}}),
    ('WINNT 6.2 cedar debug test mochitest-jetpack',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest Jetpack',
               'job_symbol': 'JP'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows8-32'}}),
    ('Ubuntu ASAN VM 12.04 x64 cedar opt test mochitest-webgl',
     {'build_type': 'asan',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest WebGL',
               'job_symbol': 'gl'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Android 4.0 Panda build-system debug test mochitest-gl',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest WebGL',
               'job_symbol': 'gl'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0'}}),
    ('Android 2.3 Emulator try opt test mochitest-gl-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest WebGL',
               'job_symbol': 'gl1'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-3'}}),
    ('Android 2.3 Emulator try opt test mochitest-gl-2',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest WebGL',
               'job_symbol': 'gl2'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-3'}}),
    ('b2g_mozilla-inbound_wasabi_dep',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'Wasabi Device Image',
               'group_symbol': 'Wasabi',
               'name': 'Wasabi Device Image Build',
               'job_symbol': 'B'},
      'platform': {'arch': 'armv7',
                   'os': 'b2g',
                   'os_platform': 'b2g-device-image'}}),
    ('jetpack-fx-team-ubuntu64-asan_vm-opt',
     {'build_type': 'asan',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Jetpack SDK Test',
               'job_symbol': 'JP'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu VM 12.04 x64 mozilla-central opt test web-platform-tests-3',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'W3C Web Platform Tests',
               'group_symbol': 'W',
               'name': 'W3C Web Platform Tests',
               'job_symbol': '3'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Rev5 MacOSX Yosemite 10.10 cedar debug test web-platform-tests-reftests',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'W3C Web Platform Tests',
               'group_symbol': 'W',
               'name': 'W3C Web Platform Reftests',
               'job_symbol': 'Wr'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Ubuntu VM 12.04 x64 mozilla-central opt test web-platform-tests-e10s-3',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'W3C Web Platform Tests e10s',
               'group_symbol': 'W-e10s',
               'name': 'W3C Web Platform Tests e10s',
               'job_symbol': '3'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Rev5 MacOSX Yosemite 10.10 cedar debug test web-platform-tests-reftests-e10s',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'W3C Web Platform Tests e10s',
               'group_symbol': 'W-e10s',
               'name': 'W3C Web Platform Reftests e10s',
               'job_symbol': 'Wr-e10s'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Ubuntu VM 12.04 x64 mozilla-central opt test media-tests',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'VideoPuppeteer',
               'group_symbol': 'VP',
               'name': 'Media Tests MSE Video Playback',
               'job_symbol': 'b-m'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu VM 12.04 x64 mozilla-central opt test media-youtube-tests',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'VideoPuppeteer',
               'group_symbol': 'VP',
               'name': 'Media Tests MSE YouTube Playback',
               'job_symbol': 'b-y'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Ubuntu HW 12.04 holly talos svgr-e10s',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance e10s',
               'group_symbol': 'T-e10s',
               'name': 'Talos svg e10s',
               'job_symbol': 's'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('WINNT 6.2 holly talos tp5o-e10s',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance e10s',
               'group_symbol': 'T-e10s',
               'name': 'Talos tp e10s',
               'job_symbol': 'tp'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows8-32'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos tp5o-osx-e10s',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance e10s',
               'group_symbol': 'T-e10s',
               'name': 'Talos tp e10s',
               'job_symbol': 'tp'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos tp5o-osx',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos tp',
               'job_symbol': 'tp'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos svgr-osx',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos svg',
               'job_symbol': 's'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos other-osx',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos other',
               'job_symbol': 'o'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos chromez-osx-e10s',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance e10s',
               'group_symbol': 'T-e10s',
               'name': 'Talos chrome e10s',
               'job_symbol': 'c'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos g1-osx-e10s',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance e10s',
               'group_symbol': 'T-e10s',
               'name': 'Talos g1 e10s',
               'job_symbol': 'g1'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos g2-osx-e10s',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance e10s',
               'group_symbol': 'T-e10s',
               'name': 'Talos g2 e10s',
               'job_symbol': 'g2'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Rev5 MacOSX Yosemite 10.10 mozilla-central talos other-osx-e10s',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance e10s',
               'group_symbol': 'T-e10s',
               'name': 'Talos other e10s',
               'job_symbol': 'o'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('WINNT 6.2 holly opt test mochitest-csb-1',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest csb',
               'group_symbol': 'M-csb',
               'name': 'Mochitest csb',
               'job_symbol': '1'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows8-32'}}),
    ('Android 4.0 Panda cedar opt test instrumentation-background',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Android Instrumentation Tests',
               'group_symbol': 'I',
               'name': 'Android Instrumentation Background',
               'job_symbol': "Ba"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0'}}),
    ('Android 4.0 Panda cedar opt test instrumentation-browser',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Android Instrumentation Tests',
               'group_symbol': 'I',
               'name': 'Android Instrumentation Browser',
               'job_symbol': "Br"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0'}}),
    ('Android armv7 API 9 cedar debug build',
     {'build_type': 'debug',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Build',
               'job_symbol': "B"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-3-armv7-api9'}}),
    ('Android armv7 API 9 cedar opt test plain-reftest-8',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Reftest',
               'job_symbol': "R8"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-2-3-armv7-api9'}}),
    ('Android armv7 API 10+ cedar non-unified',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Non-Unified Build',
               'job_symbol': "Bn"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0-armv7-api10'}}),
    ('Android 4.0 armv7 API 10+ cedar talos remote-trobocheck2',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos robocheck2',
               'job_symbol': "rck2"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0-armv7-api10'}}),
    ('Android armv7 API 15+ cedar non-unified',
     {'build_type': 'opt',
      'job_type': 'build',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'Non-Unified Build',
               'job_symbol': "Bn"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0-armv7-api15'}}),
    ('Android 4.0 armv7 API 15+ cedar talos remote-trobocheck2',
     {'build_type': 'opt',
      'job_type': 'talos',
      'name': {'group_name': 'Talos Performance',
               'group_symbol': 'T',
               'name': 'Talos robocheck2',
               'job_symbol': "rck2"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-0-armv7-api15'}}),
    ('Android 4.4 armv7 API 15+ mozilla-central opt test mochitest-8',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'Mochitest',
               'group_symbol': 'M',
               'name': 'Mochitest',
               'job_symbol': '8'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-4-armv7-api15'}}),
    ('Android 4.4 armv7 API 15+ fx-team debug test plain-reftest-3',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Reftest',
               'job_symbol': "R3"},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-4-armv7-api15'}}),
    ('Android 4.3 armv7 API 15+ mozilla-inbound opt test cppunit',
     {'build_type': 'opt',
      'job_type': 'unittest',
      'name': {'group_name': 'unknown',
               'group_symbol': '?',
               'name': 'CPP Unit Tests',
               'job_symbol': 'Cpp'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-3-armv7-api15'}}),
    ('Android 4.3 armv7 API 15+ mozilla-central debug test crashtest',
     {'build_type': 'debug',
      'job_type': 'unittest',
      'name': {'group_name': 'Reftest',
               'group_symbol': 'R',
               'name': 'Crashtest',
               'job_symbol': 'C'},
      'platform': {'arch': 'armv7',
                   'os': 'android',
                   'os_platform': 'android-4-3-armv7-api15'}}),
    ('Firefox mozilla-central linux l10n nightly-1',
     {'build_type': 'opt',
      'job_type': 'repack',
      'name': {'group_name': 'L10n Repack',
               'group_symbol': 'L10n',
               'name': 'L10n Nightly',
               'job_symbol': 'N1'},
      'platform': {'arch': 'x86',
                   'os': 'linux',
                   'os_platform': 'linux32'}}),
    ('Firefox mozilla-central linux64 l10n nightly-2',
     {'build_type': 'opt',
      'job_type': 'repack',
      'name': {'group_name': 'L10n Repack',
               'group_symbol': 'L10n',
               'name': 'L10n Nightly',
               'job_symbol': 'N2'},
      'platform': {'arch': 'x86_64',
                   'os': 'linux',
                   'os_platform': 'linux64'}}),
    ('Firefox mozilla-central macosx64 l10n nightly-3',
     {'build_type': 'opt',
      'job_type': 'repack',
      'name': {'group_name': 'L10n Repack',
               'group_symbol': 'L10n',
               'name': 'L10n Nightly',
               'job_symbol': 'N3'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('Firefox mozilla-central win32 l10n nightly-4',
     {'build_type': 'opt',
      'job_type': 'repack',
      'name': {'group_name': 'L10n Repack',
               'group_symbol': 'L10n',
               'name': 'L10n Nightly',
               'job_symbol': 'N4'},
      'platform': {'arch': 'x86',
                   'os': 'win',
                   'os_platform': 'windows8-32'}}),
    ('Firefox mozilla-central win64 l10n nightly-2',
     {'build_type': 'opt',
      'job_type': 'repack',
      'name': {'group_name': 'L10n Repack',
               'group_symbol': 'L10n',
               'name': 'L10n Nightly',
               'job_symbol': 'N2'},
      'platform': {'arch': 'x86_64',
                   'os': 'win',
                   'os_platform': 'windows8-64'}}),
    ('Firefox try macosx64 l10n',
     {'build_type': 'opt',
      'job_type': 'repack',
      'name': {'group_name': 'L10n Repack',
               'group_symbol': 'L10n',
               'name': 'L10n Repack',
               'job_symbol': 'L10n'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
    ('release-mozilla-beta_firefox_macosx64_l10n_repack',
     {'build_type': 'opt',
      'job_type': 'repack',
      'name': {'group_name': 'L10n Repack',
               'group_symbol': 'L10n',
               'name': 'L10n Repack',
               'job_symbol': 'L10n'},
      'platform': {'arch': 'x86_64',
                   'os': 'mac',
                   'os_platform': 'osx-10-10'}}),
]


@pytest.mark.parametrize(('buildername', 'exp_result'), buildernames)
def test_buildername_translation(buildername, exp_result):
    """
    test getting the right platform based on the buildername
    """

    assert buildbot.extract_platform_info(buildername) == exp_result["platform"]
    assert buildbot.extract_job_type(buildername, default="not found") == exp_result["job_type"]
    assert buildbot.extract_build_type(buildername) == exp_result["build_type"]
    assert buildbot.extract_name_info(buildername) == exp_result["name"]
